// What every tarantula shares.
const MYGALE_SEXING = "Sur une mue (exuvie), la femelle montre une poche (spermathèque) entre les premiers poumons, absente chez le mâle. Le mâle adulte a des bulbes au bout des pédipalpes et souvent des crochets sur les pattes avant.";
const MYGALE_MATING = "Présenter le mâle adulte à une femelle bien nourrie, en restant prêt à les séparer. Quelques semaines plus tard, la femelle tisse un cocon d'œufs qu'elle garde.";
const CITES = 'Espèce CITES (annexe II) : garder la facture ou le certificat de cession';

module.exports = [
  {
    category: 'arachnide', common_name: 'Vinaigrier géant', scientific_name: 'Mastigoproctus giganteus',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: "Projette un liquide acide (odeur de vinaigre) ; pince avec ses pédipalpes",
    presentation: "Le plus grand uropyge (jusqu'à 8 cm sans le fouet), du sud des États-Unis et du Mexique. Nocturne, il creuse un terrier et projette de l'acide acétique quand on l'embête.",
    habitat: "Bac plus large que haut, 10 à 15 cm de substrat humide qui tient (terre, fibre de coco), écorce de liège pour démarrer un terrier. Une coupelle d'eau peu profonde.",
    feeding_detail: "Grillons, blattes, ténébrions ; une à deux proies par semaine pour un adulte.",
    repro_sexing: "Le mâle a des pédipalpes plus longs et plus massifs que la femelle.",
    repro_conditions: "Femelle adulte bien nourrie, substrat profond pour son terrier.",
    repro_mating: "Parade où le mâle guide la femelle ; elle s'enferme ensuite dans son terrier avec un sac d'œufs sous l'abdomen.",
    repro_incubation: "Plusieurs semaines dans le terrier, sans nourrir la femelle.",
    repro_juveniles: "Les petits restent sur le dos de la mère jusqu'à leur première mue, puis se dispersent : les séparer.",
    repro_pitfalls: "Déranger la femelle dans son terrier, substrat trop mince ou sec.",
    lifespan: '4 à 8 ans (estimation)', size_class: 'moyen'
  },
  {
    category: 'arachnide', common_name: 'Amblypyge de Tanzanie', scientific_name: 'Damon diadema',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 28,
    sociability: 'Solitaire, parfois tolérant', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Inoffensif mais fragile et très rapide',
    presentation: "Arachnide d'Afrique de l'Est à l'allure de crabe-araignée, aux pattes avant transformées en longs fouets sensoriels (20 cm d'envergure). Sans venin ni soie, il vit sur les surfaces verticales.",
    habitat: "Bac plus haut que large, plaque de liège verticale contre le fond, substrat humide de 5 cm. Il mue suspendu à la tête en bas : prévoir de la hauteur.",
    feeding_detail: "Grillons, blattes, une à deux fois par semaine.",
    repro_sexing: "Difficile ; les mâles ont souvent des pédipalpes plus longs.",
    repro_conditions: "Humidité stable, adultes bien nourris.",
    repro_mating: "Le mâle dépose un sac de sperme au sol et guide la femelle dessus. Elle porte ensuite ses œufs sous l'abdomen.",
    repro_incubation: "Environ 3 mois sous la femelle.",
    repro_juveniles: "Les petits montent sur le dos de la mère, puis s'en vont après une mue.",
    repro_pitfalls: "Bac trop bas ou trop sec (mue ratée, souvent fatale).",
    lifespan: '5 à 10 ans', size_class: 'moyen', niche: 'surface'
  },
  {
    category: 'arachnide', common_name: 'Amblypyge de Floride', scientific_name: 'Phrynus marginemaculatus',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 22, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : petits grillons, blattes',
    vigilance: 'Inoffensif',
    presentation: "Petit amblypyge (2 à 3 cm de corps) de Floride et des Caraïbes, qui se reproduit bien en captivité.",
    habitat: "Petit bac vertical, liège, substrat humide.",
    feeding_detail: "Petits grillons, jeunes blattes.",
    repro_sexing: "Difficile à l'œil.",
    repro_conditions: "Humidité stable.",
    repro_mating: "Sac de sperme déposé au sol ; la femelle porte ensuite ses œufs.",
    repro_incubation: "Environ 2 à 3 mois.",
    repro_juveniles: "Petits sur le dos de la mère, puis à séparer.",
    repro_pitfalls: "Mues ratées en bac trop sec.",
    lifespan: '3 à 5 ans (estimation)', size_class: 'petit', niche: 'surface'
  },
  {
    category: 'arachnide', common_name: 'Scorpion empereur', scientific_name: 'Pandinus imperator',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 30,
    sociability: 'Groupe possible avec beaucoup de place', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: CITES + ' ; pinces fortes, venin faible',
    presentation: "Grand scorpion noir d'Afrique de l'Ouest (15 à 20 cm). Il se défend surtout avec ses pinces ; son venin est faible.",
    habitat: "Bac plus large que haut, 10 à 15 cm de substrat humide (terre, fibre de coco), écorces et cachettes, coupelle d'eau.",
    feeding_detail: "Grillons, blattes ; une à deux proies par semaine.",
    repro_sexing: "Sous l'animal, les peignes (pectines) sont plus grands chez le mâle ; la femelle est plus massive.",
    repro_conditions: "Chaleur stable, nourriture régulière.",
    repro_mating: "Danse nuptiale où le mâle tient la femelle par les pinces et dépose un sac de sperme.",
    repro_incubation: "Gestation de 7 à 9 mois : les petits naissent vivants.",
    repro_juveniles: "Les petits (10 à 30) montent sur le dos de la mère jusqu'à leur première mue.",
    repro_pitfalls: "Bac trop sec, groupe trop serré.",
    lifespan: '6 à 8 ans', size_class: 'grand'
  },
  {
    category: 'arachnide', common_name: 'Scorpion géant de forêt', scientific_name: 'Heterometrus spinifer',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 30,
    sociability: 'Solitaire de préférence', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Plus nerveux que le scorpion empereur ; piqûre douloureuse',
    presentation: "Grand scorpion noir-bleuté d'Asie du Sud-Est (12 à 15 cm). Il ressemble au scorpion empereur, en plus vif.",
    habitat: "Comme le scorpion empereur : substrat humide profond, cachettes, coupelle d'eau.",
    feeding_detail: "Grillons, blattes, une à deux fois par semaine.",
    repro_sexing: "Peignes (pectines) plus grands chez le mâle.",
    repro_conditions: "Chaleur et humidité stables.",
    repro_mating: "Danse nuptiale et sac de sperme.",
    repro_incubation: "Gestation de plusieurs mois ; naissance de petits vivants.",
    repro_juveniles: "Petits sur le dos de la mère jusqu'à la première mue.",
    repro_pitfalls: "Bac sec, plusieurs adultes ensemble.",
    lifespan: '5 à 8 ans', size_class: 'grand'
  },
  {
    category: 'arachnide', common_name: 'Scorpion plat des rochers', scientific_name: 'Hadogenes troglodytes',
    difficulty: 3, humidity_min: 40, humidity_max: 60, temp_min: 24, temp_max: 30,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Venin très faible ; très calme',
    presentation: "Scorpion d'Afrique australe, très plat, qui vit dans les fentes des rochers. Les mâles ont une queue démesurée (jusqu'à 20 cm de long en tout). Très calme, lent à grandir et à vivre longtemps.",
    habitat: "Pierres plates ou plaques de liège serrées pour créer des fentes, substrat sec (sable et terre), un coin légèrement humide et une coupelle d'eau.",
    feeding_detail: "Grillons, blattes, une fois par semaine ou moins.",
    repro_sexing: "Le mâle a une queue bien plus longue et fine que la femelle.",
    repro_conditions: "Reproduction rare et lente en captivité.",
    repro_mating: "Danse nuptiale et sac de sperme.",
    repro_incubation: "Gestation longue, souvent plus d'un an.",
    repro_juveniles: "Petits sur le dos de la mère ; croissance de plusieurs années.",
    repro_pitfalls: "Bac humide, manque de fentes pour se cacher.",
    lifespan: "jusqu'à 20 ans et plus", size_class: 'grand', niche: 'litiere', substrate_type: 'sec'
  },
  {
    category: 'arachnide', common_name: 'Mygale à poils bouclés', scientific_name: 'Tliltocatl albopilosus',
    difficulty: 1, humidity_min: 65, humidity_max: 75, temp_min: 22, temp_max: 27,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Poils urticants qu’elle projette ; ' + CITES.charAt(0).toLowerCase() + CITES.slice(1) + ' (ex-Brachypelma)',
    presentation: "Mygale terrestre d'Amérique centrale (12 à 14 cm de pattes) couverte de poils dorés bouclés. Calme, robuste, parfaite pour débuter.",
    habitat: "Bac plus large que haut, 8 à 10 cm de substrat (terreau, fibre de coco) légèrement humide, une cachette, une coupelle d'eau.",
    feeding_detail: "Grillons ou blattes, une fois par semaine pour une adulte. Ne pas nourrir avant et juste après une mue.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Femelle bien nourrie, mâle adulte de quelques semaines.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "6 à 8 semaines dans le cocon.",
    repro_juveniles: "Plusieurs centaines de petits, à élever chacun dans un petit pot.",
    repro_pitfalls: "Mâle laissé avec la femelle après l'accouplement.",
    lifespan: 'femelle 15 à 20 ans, mâle 3 à 5 ans', size_class: 'grand'
  },
  {
    category: 'arachnide', common_name: 'Mygale à genoux rouges du Mexique', scientific_name: 'Brachypelma hamorii',
    difficulty: 2, humidity_min: 60, humidity_max: 70, temp_min: 22, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Poils urticants ; ' + CITES.charAt(0).toLowerCase() + CITES.slice(1),
    presentation: "La mygale aux genoux orange et rouge du Mexique, longtemps vendue sous le nom de Brachypelma smithi. Calme et très longue à vivre.",
    habitat: "Substrat plutôt sec de 8 à 10 cm, une cachette, une coupelle d'eau.",
    feeding_detail: "Grillons, blattes, une fois par semaine pour une adulte.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Femelle adulte bien nourrie.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "Environ 2 mois dans le cocon.",
    repro_juveniles: "Nombreux petits, croissance lente.",
    repro_pitfalls: "Substrat détrempé, mâle laissé avec la femelle.",
    lifespan: 'femelle 20 à 30 ans, mâle 4 à 5 ans', size_class: 'grand', substrate_type: 'sec'
  },
  {
    category: 'arachnide', common_name: 'Mygale noire du Brésil', scientific_name: 'Grammostola pulchra',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 22, temp_max: 26,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Poils urticants',
    presentation: "Mygale d'un noir velours (14 à 16 cm de pattes), du sud du Brésil et d'Uruguay. Très calme, mais d'une croissance très lente.",
    habitat: "Substrat légèrement humide de 8 cm, cachette, coupelle d'eau. Température d'intérieur.",
    feeding_detail: "Grillons, blattes, une fois par semaine ou moins.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Femelle âgée et bien nourrie ; une période plus fraîche en hiver aide.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Croissance très lente : plusieurs années avant l'adulte.",
    repro_pitfalls: "Impatience : la reproduction prend des années.",
    lifespan: 'femelle 20 ans et plus, mâle 5 à 6 ans', size_class: 'grand'
  },
  {
    category: 'arachnide', common_name: 'Mygale bleue et verte', scientific_name: 'Chromatopelma cyaneopubescens',
    difficulty: 2, humidity_min: 50, humidity_max: 65, temp_min: 24, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Nerveuse, poils urticants',
    presentation: "Mygale du Venezuela aux pattes bleu métallique, au corps vert et à l'abdomen orange. Elle tisse beaucoup de soie.",
    habitat: "Substrat sec de 5 à 8 cm, écorces et branches pour accrocher sa toile, une coupelle d'eau. Aération.",
    feeding_detail: "Grillons, blattes, une fois par semaine.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Femelle bien nourrie.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "6 à 8 semaines.",
    repro_juveniles: "Croissance assez rapide pour une mygale.",
    repro_pitfalls: "Bac humide et confiné.",
    lifespan: 'femelle 12 à 15 ans, mâle 3 à 4 ans', size_class: 'moyen', niche: 'surface', substrate_type: 'sec'
  },
  {
    category: 'arachnide', common_name: 'Mygale arboricole de la Martinique', scientific_name: 'Caribena versicolor',
    difficulty: 3, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : grillons, blattes',
    vigilance: 'Rapide ; petits fragiles',
    presentation: "Mygale des arbres de la Martinique, bleu-vert métallique adulte, bleue rayée de rouge en juvénile. Une des plus belles, mais sensible à l'air confiné.",
    habitat: "Bac plus haut que large avec aération croisée (aérations en bas et en haut), écorce de liège verticale, plantes. Humidité élevée sans eau stagnante.",
    feeding_detail: "Grillons, blattes, une fois par semaine.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Aération et humidité stables.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "6 à 8 semaines.",
    repro_juveniles: "Petits délicats, à élever en pots bien aérés.",
    repro_pitfalls: "Bac confiné et détrempé : première cause de mortalité.",
    lifespan: 'femelle 10 à 12 ans, mâle 3 ans', size_class: 'moyen', niche: 'surface'
  },
  {
    category: 'arachnide', common_name: 'Mygale saumon du Brésil', scientific_name: 'Lasiodora parahybana',
    difficulty: 1, humidity_min: 65, humidity_max: 75, temp_min: 22, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur vorace : grillons, blattes',
    vigilance: 'Poils urticants très irritants',
    presentation: "Une des plus grandes mygales (jusqu'à 25 cm de pattes), brune aux poils saumon. Vorace et rapide à grandir.",
    habitat: "Grand bac, 10 cm de substrat légèrement humide, cachette, coupelle d'eau.",
    feeding_detail: "Grosses blattes, grillons ; mange beaucoup.",
    repro_sexing: MYGALE_SEXING,
    repro_conditions: "Femelle bien nourrie.",
    repro_mating: MYGALE_MATING,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Cocons de plus de mille petits.",
    repro_pitfalls: "Trop de petits à placer.",
    lifespan: 'femelle 15 à 20 ans, mâle 3 à 4 ans', size_class: 'grand'
  },
  {
    category: 'arachnide', common_name: 'Saltique royale', scientific_name: 'Phidippus regius',
    difficulty: 2, humidity_min: 50, humidity_max: 70, temp_min: 22, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Prédateur : mouches, petits grillons',
    vigilance: 'Aucune',
    presentation: "Grande araignée sauteuse de Floride (1,5 à 2 cm), curieuse et active le jour, qui suit du regard ce qui bouge. Une araignée très attachante.",
    habitat: "Petit bac plus haut que large, bien aéré, branches et feuilles, coin en haut pour son nid de soie. Brumisage léger 2 fois par semaine.",
    feeding_detail: "Mouches, petits grillons, une à deux fois par semaine.",
    repro_sexing: "Le mâle adulte est noir à bandes blanches, avec des pédipalpes renflés ; la femelle est souvent grise ou orangée.",
    repro_conditions: "Femelle bien nourrie.",
    repro_mating: "Parade dansée du mâle ; la femelle pond plusieurs cocons dans son nid.",
    repro_incubation: "Environ 3 à 4 semaines.",
    repro_juveniles: "Des dizaines à centaines de petits, à séparer et nourrir de drosophiles.",
    repro_pitfalls: "Bac sans aération, jeunes laissés ensemble.",
    lifespan: '1 à 2 ans', size_class: 'petit', niche: 'surface'
  }
];
