// Blaberidae carry their egg case inside the body and give birth to live
// nymphs; Blattidae and Corydiidae lay it in the substrate.
const LIVE_BIRTH = "La femelle forme une oothèque qu'elle garde à l'intérieur de son corps : les petits naissent vivants.";

module.exports = [
  {
    category: 'blatte', common_name: 'Blatte siffleuse de Madagascar', scientific_name: 'Gromphadorhina portentosa',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 24, temp_max: 30,
    sociability: 'Colonie ; les mâles se disputent sans se blesser', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Grimpe sur le verre : couvercle bien fermé',
    presentation: "La plus célèbre des blattes d'élevage : 5 à 7,5 cm, sans ailes, lente et calme. Elle siffle en chassant l'air par les orifices respiratoires de son abdomen, pour se défendre ou pendant les combats entre mâles.",
    habitat: "Bac aéré, 3 à 5 cm de fibre de coco ou de terreau, écorces de liège dressées et boîtes à œufs pour grimper. Une bande de vaseline ou d'antigrimpe en haut des parois limite les sorties. Chaleur de 26 à 28 °C pour une reproduction régulière.",
    feeding_detail: "Fruits et légumes frais (pomme, carotte, courgette, salade), croquettes pour chat ou poisson en complément. Les fruits juteux ou un gel d'eau suffisent pour boire ; éviter l'eau libre où les petits se noient.",
    repro_sexing: "Le mâle a deux grosses bosses (cornes) sur le pronotum et des antennes plus épaisses et poilues ; la femelle a un pronotum presque lisse.",
    repro_conditions: "Chaleur (26-30 °C), nourriture variée et abondante. En dessous de 22 °C, la reproduction s'arrête presque.",
    repro_mating: "Accouplement dos à dos, abdomens joints. " + LIVE_BIRTH,
    repro_incubation: "Environ 2 mois de gestation à bonne température.",
    repro_juveniles: "20 à 40 petits par portée, blancs à la naissance. Six mues et 5 à 7 mois pour devenir adultes.",
    repro_pitfalls: "Froid, couvercle mal fermé, eau stagnante. Les petits acariens qu'elles portent souvent sont inoffensifs (ils vivent avec elles).",
    lifespan: '2 à 5 ans'
  },
  {
    category: 'blatte', common_name: 'Blatte siffleuse naine', scientific_name: 'Elliptorhina javanica',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Grimpe sur le verre : couvercle bien fermé',
    presentation: "Petite cousine malgache des grandes siffleuses (3 à 4 cm), brune lustrée. Elle siffle aussi, prend peu de place et se reproduit bien.",
    habitat: "Petit bac aéré, fibre de coco, écorces et boîtes à œufs. Chaleur de 26 à 28 °C.",
    feeding_detail: "Fruits, légumes, croquettes, un peu de protéines.",
    repro_sexing: "Le mâle a des bosses sur le pronotum et des antennes plus épaisses ; la femelle est plus lisse et plus large.",
    repro_conditions: "Chaleur et nourriture variée.",
    repro_mating: "Accouplement dos à dos. " + LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "15 à 30 petits par portée ; adultes en 4 à 6 mois.",
    repro_pitfalls: "Froid, fuites par le couvercle.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'blatte', common_name: 'Blatte siffleuse tigrée', scientific_name: 'Princisia vanwaerebeki',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 24, temp_max: 30,
    sociability: 'Colonie ; mâles territoriaux', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Grimpe sur le verre : couvercle bien fermé',
    presentation: "Grande siffleuse de Madagascar (6 à 8 cm) rayée de bandes claires, dont les mâles portent des cornes très développées. Plus spectaculaire que la siffleuse classique, aussi facile.",
    habitat: "Bac aéré assez grand, fibre de coco, beaucoup d'écorces dressées pour que les mâles aient chacun leur territoire.",
    feeding_detail: "Fruits, légumes, croquettes.",
    repro_sexing: "Mâle : cornes massives sur le pronotum ; femelle : pronotum lisse.",
    repro_conditions: "Chaleur, place et cachettes.",
    repro_mating: "Accouplement dos à dos. " + LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Portées de 20 à 40 petits ; adultes en 6 à 8 mois.",
    repro_pitfalls: "Trop de mâles dans un petit bac, froid.",
    lifespan: '2 à 4 ans'
  },
  {
    category: 'blatte', common_name: "Blatte d'Argentine (dubia)", scientific_name: 'Blaptica dubia',
    difficulty: 1, humidity_min: 50, humidity_max: 65, temp_min: 26, temp_max: 32,
    sociability: 'Colonie très nombreuse', diet_summary: 'Omnivore : légumes, fruits, céréales',
    vigilance: 'Aucune : ne grimpe pas le verre, ne vole pas',
    presentation: "La blatte nourricière par excellence : 4 à 4,5 cm, silencieuse, sans odeur, incapable de grimper les parois lisses. Parfaite pour nourrir réduves, crabes ou uropyges.",
    habitat: "Bac lisse et aéré (pas besoin de couvercle étanche), boîtes à œufs empilées, sans substrat ou avec un peu de fibre de coco. Chaleur de 28 à 32 °C pour une production soutenue.",
    feeding_detail: "Légumes et fruits (carotte, orange, pomme), flocons de céréales, croquettes. Les agrumes et les carottes stimulent la ponte.",
    repro_sexing: "Le mâle a des ailes complètes qui couvrent l'abdomen (il ne vole pas) ; la femelle n'a que de courts moignons d'ailes.",
    repro_conditions: "La chaleur est la clé : en dessous de 26 °C, la colonie stagne.",
    repro_mating: "Accouplement dos à dos. " + LIVE_BIRTH,
    repro_incubation: "Environ 1 mois à 30 °C.",
    repro_juveniles: "20 à 40 petits par portée ; adultes en 4 à 6 mois.",
    repro_pitfalls: "Froid, humidité excessive (moisissures, odeurs), nourriture qui pourrit.",
    lifespan: '1 à 2 ans', feed_every_days: 3, substrate_type: 'sec'
  },
  {
    category: 'blatte', common_name: 'Blatte turkestan', scientific_name: 'Shelfordella lateralis',
    difficulty: 1, humidity_min: 40, humidity_max: 60, temp_min: 26, temp_max: 32,
    sociability: 'Colonie très nombreuse', diet_summary: 'Omnivore vorace',
    vigilance: 'Très rapide : attention aux fuites',
    presentation: "Petite blatte nourricière (2,5 cm) très prolifique et rapide, qui ne grimpe pas le verre. Les mâles sont ailés et rayés de clair, les femelles plus foncées avec des marques crème.",
    habitat: "Bac lisse avec couvercle aéré, boîtes à œufs, un coin de fibre de coco légèrement humide pour la ponte. Chaleur de 28 à 32 °C.",
    feeding_detail: "Légumes, fruits, céréales, croquettes : elle mange beaucoup et vite.",
    repro_sexing: "Mâle : ailes longues et corps fin ; femelle : ailes courtes, corps large, taches crème.",
    repro_conditions: "Chaleur et nourriture abondante.",
    repro_mating: "La femelle dépose ses oothèques (environ 16 œufs) dans le substrat humide.",
    repro_incubation: "4 à 6 semaines à 30 °C.",
    repro_juveniles: "Adultes en 3 à 4 mois.",
    repro_pitfalls: "Fuites (elle court vite à l'ouverture), substrat de ponte trop sec.",
    lifespan: 'environ 1 an', feed_every_days: 2, substrate_type: 'sec'
  },
  {
    category: 'blatte', common_name: 'Blatte tête de mort', scientific_name: 'Blaberus craniifer',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 25, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Aucune : ne grimpe pas le verre',
    presentation: "Grande blatte d'Amérique centrale (5 à 6 cm) dont le pronotum porte un dessin rappelant une tête de mort. Calme, facile, et les jeunes s'enterrent.",
    habitat: "Bac lisse, 5 cm de fibre de coco ou de terreau pour les jeunes fouisseurs, écorces et boîtes à œufs.",
    feeding_detail: "Fruits, légumes, croquettes, un peu de protéines.",
    repro_sexing: "Le mâle a l'abdomen plus fin avec des styles au bout (petits filaments) ; la femelle, plus large, n'en a pas.",
    repro_conditions: "Chaleur et nourriture variée.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "20 à 40 petits par portée ; adultes en 5 à 7 mois.",
    repro_pitfalls: "Substrat trop sec pour les jeunes, froid.",
    lifespan: '1 an et demi à 2 ans'
  },
  {
    category: 'blatte', common_name: "Blatte géante d'Amérique centrale", scientific_name: 'Blaberus giganteus',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 26, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Aucune : ne grimpe pas le verre',
    presentation: "Une des plus grandes blattes du monde : 7,5 à 10 cm, ailes brun clair et pronotum taché de noir. Lente à grandir, impressionnante en adulte.",
    habitat: "Grand bac, substrat de 5 à 8 cm, beaucoup d'écorces de liège dressées. Humidité élevée et chaleur stable.",
    feeding_detail: "Fruits, légumes, croquettes, protéines.",
    repro_sexing: "Mâle plus fin avec des styles au bout de l'abdomen ; femelle plus large.",
    repro_conditions: "Chaleur stable (28 °C), humidité, place.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "20 à 40 petits ; environ un an pour devenir adultes.",
    repro_pitfalls: "Mues ratées si le bac est trop sec ou s'il manque de supports pour s'accrocher.",
    lifespan: 'environ 2 ans', size_class: 'grand'
  },
  {
    category: 'blatte', common_name: 'Blatte paon', scientific_name: 'Archimandrita tessellata',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 24, temp_max: 30,
    sociability: 'Colonie calme', diet_summary: 'Omnivore : fruits, légumes, feuilles',
    vigilance: 'Aucune',
    presentation: "Grande blatte d'Amérique centrale (6 à 8 cm) aux ailes mouchetées comme du poivre. Très calme, elle se manipule facilement.",
    habitat: "Grand bac, fibre de coco et feuilles mortes, écorces dressées pour grimper et muer suspendue.",
    feeding_detail: "Fruits, légumes, feuilles mortes, croquettes.",
    repro_sexing: "Mâle plus fin, ailes un peu plus longues que l'abdomen ; femelle plus large.",
    repro_conditions: "Chaleur, place, supports verticaux.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Portées moyennes ; croissance lente, environ un an.",
    repro_pitfalls: "Manque de supports pour la mue, froid.",
    lifespan: '2 à 3 ans', size_class: 'grand'
  },
  {
    category: 'blatte', common_name: 'Blatte à quatre taches', scientific_name: 'Eublaberus distanti',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 25, temp_max: 30,
    sociability: 'Colonie très nombreuse', diet_summary: 'Omnivore : tout',
    vigilance: 'Aucune : ne grimpe pas le verre',
    presentation: "Blatte fouisseuse d'Amérique du Sud (4 à 5 cm), aux quatre taches sombres sur les ailes. Très prolifique, elle sert aussi de nourriture vivante.",
    habitat: "Bac lisse, 5 à 8 cm de substrat humide (fibre de coco, feuilles), écorces.",
    feeding_detail: "Fruits, légumes, croquettes, restes.",
    repro_sexing: "Mâle plus fin avec des styles au bout de l'abdomen ; femelle plus large.",
    repro_conditions: "Chaleur et substrat humide.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "20 à 35 petits ; adultes en 4 à 6 mois.",
    repro_pitfalls: "Substrat sec, surpopulation non gérée.",
    lifespan: '1 an et demi à 2 ans', niche: 'fouisseur'
  },
  {
    category: 'blatte', common_name: 'Blatte verte de Cuba', scientific_name: 'Panchlora nivea',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 24, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes',
    vigilance: 'Grimpe le verre et les adultes volent',
    presentation: "Petite blatte (1,5 à 2,5 cm) vert pomme en adulte, tandis que les jeunes, brun foncé, vivent enterrés. Très jolie, mais rapide et volante.",
    habitat: "Bac à couvercle fin et bien fermé, substrat de 5 cm humide (fibre de coco, feuilles), écorces.",
    feeding_detail: "Fruits mûrs, légumes, un peu de croquettes.",
    repro_sexing: "Le mâle est plus petit et plus fin que la femelle.",
    repro_conditions: "Chaleur et substrat humide pour les jeunes.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 6 semaines.",
    repro_juveniles: "Les jeunes vivent dans le substrat ; adultes en 3 à 4 mois.",
    repro_pitfalls: "Fuites à l'ouverture du bac (elles volent), substrat trop sec.",
    lifespan: 'environ 1 an', size_class: 'petit'
  },
  {
    category: 'blatte', common_name: 'Blatte de Surinam', scientific_name: 'Pycnoscelus surinamensis',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 24, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : végétaux, restes',
    vigilance: 'Ne pas laisser échapper : nuisible des serres',
    presentation: "Petite blatte fouisseuse (2 cm), luisante, presque toujours enterrée. La plupart des souches ne comptent que des femelles qui se reproduisent seules.",
    habitat: "Bac lisse, 5 à 8 cm de substrat humide (terreau, fibre de coco), feuilles mortes.",
    feeding_detail: "Feuilles, légumes, fruits, croquettes.",
    repro_sexing: "Souches surtout femelles (parthénogenèse) : pas besoin de mâle.",
    repro_conditions: "Chaleur et substrat humide.",
    repro_mating: "Reproduction sans mâle. " + LIVE_BIRTH,
    repro_incubation: "Environ 5 semaines.",
    repro_juveniles: "20 à 30 petits ; adultes en 4 à 5 mois.",
    repro_pitfalls: "Évasion dans une serre ou un terrarium planté : elle abîme les racines.",
    lifespan: 'environ 1 an', size_class: 'petit', niche: 'fouisseur'
  },
  {
    category: 'blatte', common_name: 'Blatte capucin', scientific_name: 'Ergaula capucina',
    difficulty: 2, humidity_min: 50, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : feuilles, fruits, croquettes',
    vigilance: 'Les mâles volent',
    presentation: "Blatte fouisseuse d'Asie du Sud-Est : femelle ronde, sans ailes, de 3 à 4 cm, mâle ailé plus petit. Discrète, elle passe sa vie dans le substrat.",
    habitat: "8 à 10 cm de substrat (terreau, sable, feuilles) sec en surface et humide au fond, écorces.",
    feeding_detail: "Feuilles mortes, fruits, légumes, croquettes.",
    repro_sexing: "Femelle sans ailes et ronde ; mâle ailé.",
    repro_conditions: "Substrat profond avec un fond humide, chaleur.",
    repro_mating: "La femelle enterre ses oothèques dans le substrat.",
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Les jeunes restent enterrés ; croissance lente, environ un an.",
    repro_pitfalls: "Substrat entièrement sec ou détrempé, couvercle mal fermé (mâles).",
    lifespan: '1 à 2 ans', niche: 'fouisseur'
  },
  {
    category: 'blatte', common_name: 'Blatte des sables égyptienne', scientific_name: 'Polyphaga aegyptiaca',
    difficulty: 2, humidity_min: 40, humidity_max: 60, temp_min: 26, temp_max: 32,
    sociability: 'Colonie', diet_summary: 'Omnivore : feuilles sèches, céréales, fruits',
    vigilance: 'Les mâles volent',
    presentation: "Blatte du désert : femelle ronde et sans ailes, comme une petite tortue brune, mâle ailé. Elle vit enfouie dans le sable et grandit lentement.",
    habitat: "10 cm de mélange sable et terre, sec en surface et légèrement humide au fond, feuilles sèches. Chaleur.",
    feeding_detail: "Feuilles sèches, flocons de céréales, fruits, croquettes.",
    repro_sexing: "Femelle ronde sans ailes ; mâle ailé et plus fin.",
    repro_conditions: "Chaleur et fond de substrat humide.",
    repro_mating: "Oothèques enterrées dans le sable.",
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Croissance lente : 1 à 2 ans pour devenir adultes.",
    repro_pitfalls: "Trop d'humidité, froid.",
    lifespan: '2 à 3 ans', niche: 'fouisseur', substrate_type: 'sec'
  },
  {
    category: 'blatte', common_name: 'Blatte domino', scientific_name: 'Therea petiveriana',
    difficulty: 3, humidity_min: 50, humidity_max: 60, temp_min: 26, temp_max: 32,
    sociability: 'Colonie', diet_summary: 'Omnivore : feuilles, fruits, croquettes',
    vigilance: 'Aucune',
    presentation: "Blatte d'Inde (2,5 à 3 cm) noire à taches blanches comme un domino, proche de la blatte panda. Les adultes courent en surface, les jeunes vivent enterrés.",
    habitat: "8 à 10 cm de sable et terre, sec en surface et humide au fond, feuilles mortes. Chaleur.",
    feeding_detail: "Feuilles mortes, fruits, croquettes.",
    repro_sexing: "Le mâle est un peu plus petit, avec des ailes ; la femelle n'en a pas.",
    repro_conditions: "Chaleur et fond humide.",
    repro_mating: "Oothèques enterrées.",
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Croissance lente, environ un an.",
    repro_pitfalls: "Humidité excessive en surface, froid.",
    lifespan: '1 à 2 ans', size_class: 'petit', substrate_type: 'sec'
  },
  {
    category: 'blatte', common_name: 'Blatte à bordure jaune', scientific_name: 'Opisthoplatia orientalis',
    difficulty: 2, humidity_min: 60, humidity_max: 80, temp_min: 22, temp_max: 28,
    sociability: 'Colonie', diet_summary: 'Omnivore : feuilles, fruits, croquettes',
    vigilance: 'Grimpe sur le verre',
    presentation: "Blatte d'Asie (3 cm) noire bordée de jaune, sans ailes pour voler. Nocturne, elle se cache sous les écorces le jour.",
    habitat: "Substrat de 5 cm (tourbe sans engrais, feuilles, fibre de coco, un peu de sable), écorces de liège. Un tiers du bac humide.",
    feeding_detail: "Feuilles mortes, fruits, légumes, croquettes.",
    repro_sexing: "Le mâle est plus fin que la femelle.",
    repro_conditions: "Humidité partielle, cachettes.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Quelques semaines.",
    repro_juveniles: "Les jeunes s'enfouissent dans le substrat.",
    repro_pitfalls: "Bac entièrement sec, fuites par le couvercle.",
    lifespan: '1 à 2 ans (estimation)'
  },
  {
    category: 'blatte', common_name: 'Blatte de porcelaine', scientific_name: 'Gyna lurida',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Les mâles volent',
    presentation: "Petite blatte d'Afrique (2,5 à 3,5 cm) au pronotum clair et lisse comme de la porcelaine. Facile et prolifique.",
    habitat: "Substrat de 5 cm humide, écorces, boîtes à œufs.",
    feeding_detail: "Fruits, légumes, croquettes.",
    repro_sexing: "Le mâle est ailé et plus fin.",
    repro_conditions: "Chaleur et humidité.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 6 semaines.",
    repro_juveniles: "Les jeunes vivent enfouis ; adultes en 4 à 5 mois.",
    repro_pitfalls: "Substrat trop sec.",
    lifespan: 'environ 1 an', size_class: 'petit'
  },
  {
    category: 'blatte', common_name: 'Blatte fouisseuse de Cuba', scientific_name: 'Byrsotria fumigata',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 25, temp_max: 30,
    sociability: 'Colonie', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Aucune',
    presentation: "Grande blatte brune de Cuba (5 à 6 cm), calme et fouisseuse. Une espèce simple pour qui aime les grandes blattes.",
    habitat: "Substrat de 8 cm (terreau, fibre de coco), écorces.",
    feeding_detail: "Fruits, légumes, croquettes.",
    repro_sexing: "Mâle plus fin, ailes plus longues ; femelle plus large.",
    repro_conditions: "Chaleur, substrat profond.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Environ 2 mois.",
    repro_juveniles: "Adultes en 6 à 8 mois.",
    repro_pitfalls: "Substrat trop mince ou sec.",
    lifespan: '1 an et demi à 2 ans', niche: 'fouisseur'
  },
  {
    category: 'blatte', common_name: 'Blatte mangeuse de bois', scientific_name: 'Panesthia angustipennis',
    difficulty: 3, humidity_min: 70, humidity_max: 85, temp_min: 20, temp_max: 26,
    sociability: 'Familles', diet_summary: 'Bois pourri surtout',
    vigilance: 'Aucune',
    presentation: "Blatte noire et luisante d'Asie (3 à 4 cm) qui vit en familles dans le bois pourri, qu'elle creuse et mange. Les adultes perdent leurs ailes en se les grignotant.",
    habitat: "Bûches de bois blanc pourri (feuillus) dans un substrat humide de feuilles et de terreau. Elle reste presque tout le temps dans le bois.",
    feeding_detail: "Bois blanc pourri (pourriture blanche) à volonté, feuilles mortes, un peu de fruit.",
    repro_sexing: "Difficile à l'œil ; la femelle est en général plus large.",
    repro_conditions: "Du bois pourri de bonne qualité en quantité, humidité stable, calme.",
    repro_mating: LIVE_BIRTH,
    repro_incubation: "Quelques semaines.",
    repro_juveniles: "Les jeunes restent avec les parents dans les galeries ; croissance lente.",
    repro_pitfalls: "Manque de bois pourri, bac qui sèche.",
    lifespan: '2 à 3 ans (estimation)', diet_type: 'detritivore', niche: 'fouisseur'
  }
];
