// How every cétoine is sexed, and the larval life they share.
const SEXING = "Chez l'adulte, le mâle a le dessous de l'abdomen creusé d'un sillon et les pattes avant souvent plus longues ; la femelle a l'abdomen bombé.";
const LARVAE = "Les larves vivent dans le substrat et se nourrissent de terreau de feuilles et de bois décomposé.";

module.exports = [
  {
    category: 'cetoine', common_name: 'Cétoine du Soudan', scientific_name: 'Pachnoda butana',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : terreau de feuilles',
    vigilance: 'Les adultes volent',
    presentation: "Cétoine d'Afrique de l'Est (2 à 2,5 cm), jaune et noire, très proche de Pachnoda marginata. Facile, rapide et colorée.",
    habitat: "Bac aéré avec 15 cm de terreau de feuilles fermenté (flake soil) et bois pourri pour les larves, écorces et branches pour les adultes. Couvercle grillagé : les adultes volent dès qu'il fait chaud.",
    feeding_detail: "Adultes : banane, pomme, poire, gelée pour coléoptères. " + LARVAE,
    repro_sexing: SEXING,
    repro_conditions: "Substrat profond et riche, chaleur.",
    repro_mating: "Accouplements fréquents ; les femelles s'enfouissent pour pondre.",
    repro_incubation: "Environ 2 semaines.",
    repro_juveniles: "Cycle complet en 4 à 6 mois : larve, puis cocon de terre où elle se nymphose.",
    repro_pitfalls: "Substrat trop sec ou trop pauvre, cocons écrasés en fouillant.",
    lifespan: 'environ 1 an, dont 3 à 4 mois en adulte'
  },
  {
    category: 'cetoine', common_name: "Cétoine d'Afrique du Sud", scientific_name: 'Pachnoda sinuata',
    difficulty: 1, humidity_min: 60, humidity_max: 70, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : terreau de feuilles',
    vigilance: 'Les adultes volent',
    presentation: "Cétoine sud-africaine (2 cm) brun et jaune. Aussi facile que les autres Pachnoda, idéale pour débuter les cétoines.",
    habitat: "Comme les autres Pachnoda : flake soil profond, bois pourri, branches, couvercle grillagé.",
    feeding_detail: "Adultes : fruits mûrs, gelée pour coléoptères. " + LARVAE,
    repro_sexing: SEXING,
    repro_conditions: "Chaleur et substrat riche.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "Environ 2 semaines.",
    repro_juveniles: "Cycle en 4 à 6 mois.",
    repro_pitfalls: "Substrat pauvre ou sec.",
    lifespan: 'environ 1 an'
  },
  {
    category: 'cetoine', common_name: 'Cétoine à cornes de Grall', scientific_name: 'Eudicella gralli',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 27,
    sociability: 'Groupe ; mâles qui se disputent', diet_summary: 'Adultes : fruits ; larves : flake soil et protéines',
    vigilance: 'Larves parfois cannibales',
    presentation: "Cétoine d'Afrique centrale (3 à 4 cm) vert métallique, dont les mâles portent une corne fourchue sur la tête. Une des cétoines à cornes les plus faciles.",
    habitat: "Flake soil profond (15 cm) avec bois pourri, branches et écorces pour les adultes, couvercle grillagé.",
    feeding_detail: "Adultes : fruits, gelée pour coléoptères. Larves : flake soil, bois pourri, et un peu de protéines (croquettes pour chien ou poisson) qui limite le cannibalisme.",
    repro_sexing: "Le mâle porte une corne en forme de Y sur la tête ; la femelle n'en a pas.",
    repro_conditions: "Substrat riche, chaleur douce.",
    repro_mating: "Les femelles pondent dans le substrat profond.",
    repro_incubation: "Environ 2 à 3 semaines.",
    repro_juveniles: "Séparer les grosses larves (dernier stade) dans des boîtes individuelles. Cycle en 6 à 8 mois.",
    repro_pitfalls: "Larves trop serrées (cannibalisme), substrat pauvre.",
    lifespan: 'environ 1 an, dont 3 à 4 mois en adulte'
  },
  {
    category: 'cetoine', common_name: 'Cétoine de Smith', scientific_name: 'Eudicella smithii',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 27,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : flake soil et protéines',
    vigilance: 'Larves parfois cannibales',
    presentation: "Cétoine d'Afrique de l'Est (2,5 à 3 cm) verte et brune, aux mâles cornus. Même élevage que la cétoine de Grall.",
    habitat: "Flake soil profond, bois pourri, branches, couvercle grillagé.",
    feeding_detail: "Adultes : fruits, gelée pour coléoptères. Larves : flake soil, bois pourri, un peu de protéines.",
    repro_sexing: "Mâle : corne fourchue sur la tête ; femelle sans corne.",
    repro_conditions: "Substrat riche, chaleur douce.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "2 à 3 semaines.",
    repro_juveniles: "Isoler les larves du dernier stade. Cycle en 6 à 8 mois.",
    repro_pitfalls: "Cannibalisme des larves serrées.",
    lifespan: 'environ 1 an'
  },
  {
    category: 'cetoine', common_name: 'Cétoine géante verte', scientific_name: 'Mecynorrhina torquata',
    difficulty: 3, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 26,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : flake soil et beaucoup de protéines',
    vigilance: 'Larves cannibales : à séparer',
    presentation: "Une des plus grandes cétoines (5 à 8 cm), vert ou rouge métallique selon les formes. Les mâles portent une petite corne. Un élevage plus exigeant mais spectaculaire.",
    habitat: "Grand bac de ponte avec 20 cm de flake soil et de bois pourri. Larves en boîtes individuelles d'1 à 2 litres au dernier stade.",
    feeding_detail: "Adultes : fruits mûrs, gelée pour coléoptères. Larves : flake soil, bois pourri, et des protéines régulières (croquettes pour chat ou chien) : elles en ont besoin pour grossir.",
    repro_sexing: "Le mâle a une petite corne sur la tête et des pattes avant longues ; la femelle n'a pas de corne.",
    repro_conditions: "Substrat profond et riche, chaleur stable.",
    repro_mating: "Ponte dans le substrat profond.",
    repro_incubation: "Environ 3 semaines.",
    repro_juveniles: "Isoler les larves dès qu'elles grossissent. Cycle en 6 à 8 mois.",
    repro_pitfalls: "Larves ensemble (elles se tuent), manque de protéines, cocons dérangés.",
    lifespan: 'environ 1 an, dont 3 à 6 mois en adulte', size_class: 'grand'
  },
  {
    category: 'cetoine', common_name: 'Cétoine polyphème', scientific_name: 'Mecynorrhina polyphemus',
    difficulty: 3, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 26,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : flake soil et protéines',
    vigilance: 'Larves cannibales : à séparer',
    presentation: "Grande cétoine d'Afrique centrale (4 à 6 cm) vert velouté rayé de blanc, aux mâles cornus. Même élevage que la cétoine géante verte.",
    habitat: "Flake soil profond et bois pourri, boîtes individuelles pour les grosses larves.",
    feeding_detail: "Adultes : fruits, gelée. Larves : flake soil, bois pourri, protéines régulières.",
    repro_sexing: "Mâle : corne sur la tête ; femelle sans corne.",
    repro_conditions: "Substrat riche et chaleur stable.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "Environ 3 semaines.",
    repro_juveniles: "Cycle en 6 à 8 mois, larves isolées.",
    repro_pitfalls: "Cannibalisme, manque de protéines.",
    lifespan: 'environ 1 an', size_class: 'grand'
  },
  {
    category: 'cetoine', common_name: 'Cétoine tachetée', scientific_name: 'Stephanorrhina guttata',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 27,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : flake soil',
    vigilance: 'Les adultes volent',
    presentation: "Petite cétoine d'Afrique de l'Ouest (2 à 2,5 cm) vert et rouge métallique, ponctuée de blanc. Très décorative.",
    habitat: "Flake soil et bois pourri, branches, couvercle grillagé.",
    feeding_detail: "Adultes : fruits, gelée pour coléoptères. " + LARVAE,
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, substrat riche.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "Environ 2 semaines.",
    repro_juveniles: "Cycle en 5 à 7 mois.",
    repro_pitfalls: "Substrat pauvre, sec.",
    lifespan: 'environ 1 an'
  },
  {
    category: 'cetoine', common_name: "Cétoine émeraude d'Afrique", scientific_name: 'Chlorocala africana',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 27,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits ; larves : flake soil',
    vigilance: 'Les adultes volent',
    presentation: "Cétoine d'Afrique (2 à 2,5 cm) d'un vert émeraude métallique, parfois cuivré ou bleuté.",
    habitat: "Flake soil et bois pourri, branches, couvercle grillagé.",
    feeding_detail: "Adultes : fruits, gelée. " + LARVAE,
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, substrat riche.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "Environ 2 semaines.",
    repro_juveniles: "Cycle en 5 à 7 mois.",
    repro_pitfalls: "Substrat pauvre, sec.",
    lifespan: 'environ 1 an'
  },
  {
    category: 'cetoine', common_name: 'Cétoine dorée', scientific_name: 'Cetonia aurata',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 15, temp_max: 25,
    sociability: 'Groupe', diet_summary: 'Adultes : fruits, fleurs ; larves : terreau de feuilles',
    vigilance: 'Hiver au frais indispensable',
    presentation: "La cétoine verte de nos jardins (1,5 à 2 cm). Elle suit le rythme des saisons : il faut lui offrir un vrai hiver.",
    habitat: "Flake soil ou terreau de feuilles de chêne profond, bois pourri. À garder à l'extérieur abrité ou au frais l'hiver.",
    feeding_detail: "Adultes : fruits, fleurs (roses, sureau). " + LARVAE,
    repro_sexing: SEXING,
    repro_conditions: "Hiver frais (5-10 °C) pour les larves âgées et les adultes, puis printemps.",
    repro_mating: "Ponte au printemps et en été.",
    repro_incubation: "Environ 2 semaines.",
    repro_juveniles: "Cycle de 1 à 2 ans selon la température.",
    repro_pitfalls: "Garder au chaud toute l'année (cycle déréglé), substrat de résineux.",
    lifespan: '1 à 2 ans, dont quelques mois en adulte'
  },
  {
    category: 'cetoine', common_name: 'Goliath', scientific_name: 'Goliathus goliatus',
    difficulty: 5, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 26,
    sociability: 'Larves isolées', diet_summary: 'Adultes : fruits ; larves : très riches en protéines',
    vigilance: 'Élevage expert, adultes chers',
    presentation: "Un des plus gros insectes du monde (jusqu'à 11 cm), blanc et noir, aux mâles cornus. Le rêve de nombreux éleveurs de cétoines, mais l'élevage le plus exigeant du genre.",
    habitat: "Bac de ponte avec 20 cm de flake soil riche. Larves dans de grandes boîtes individuelles (5 à 10 litres) au dernier stade.",
    feeding_detail: "Adultes : fruits mûrs, gelée pour coléoptères. Larves : flake soil et beaucoup de protéines (croquettes pour chien ou chat, nourriture pour poissons) : elles sont en partie carnivores.",
    repro_sexing: "Mâle : corne en Y sur la tête ; femelle sans corne, tête en forme de pelle.",
    repro_conditions: "Chaleur stable, substrat riche, apport de protéines constant aux larves.",
    repro_mating: "Ponte dans le substrat profond.",
    repro_incubation: "Environ 3 semaines.",
    repro_juveniles: "Larves isolées tôt ; cycle d'environ 1 an.",
    repro_pitfalls: "Protéines insuffisantes (adultes petits ou mortalité), larves ensemble, chocs thermiques.",
    lifespan: 'environ 1 an, dont quelques mois en adulte', size_class: 'grand'
  }
];
