// Sexing is the same for every cloporte, so it is said once.
const SEXING = "Sous l'animal, le mâle porte au début de l'abdomen deux pièces allongées en pointe (pléopodes modifiés) que la femelle n'a pas. Une femelle qui porte a le ventre gonflé d'une poche blanchâtre (marsupium).";

module.exports = [
  {
    category: 'cloporte', common_name: "Cloporte 'Papaya'", scientific_name: 'Cubaris murina "Papaya"',
    difficulty: 2, humidity_min: 70, humidity_max: 85, temp_min: 21, temp_max: 28,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, protéines',
    vigilance: 'Aucune',
    presentation: "Forme orange marbrée de blanc du petit Cubaris des tropiques (environ 1 cm). Il se roule en boule, se reproduit bien et reste l'une des portes d'entrée les plus faciles vers les Cubaris.",
    habitat: "Substrat de 5 à 8 cm (terreau de feuilles, fibre de coco, bois pourri), feuilles mortes, écorce de liège. Deux tiers du bac humides, un tiers plus sec, aération correcte.",
    feeding_detail: "Feuilles mortes (chêne, catappa), bois pourri, légumes, et des protéines chaque semaine (granulés pour poissons, crevettes séchées). Calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur douce (24-26 °C), humidité stable et protéines régulières : la colonie démarre vite.",
    repro_mating: "Accouplements toute l'année ; la femelle porte les œufs dans son marsupium.",
    repro_incubation: "Environ 4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Les petits (mancas) sont blancs à la naissance ; adultes en 3 à 5 mois.",
    repro_pitfalls: "Bac confiné sans aération, manque de protéines (cannibalisme des mues), substrat entièrement détrempé.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'cloporte', common_name: "Cloporte 'Rubber Ducky'", scientific_name: 'Cubaris sp. "Rubber Ducky"',
    difficulty: 4, humidity_min: 75, humidity_max: 85, temp_min: 21, temp_max: 26,
    sociability: 'Petite colonie calme', diet_summary: 'Détritivore : feuilles, bois, mousse',
    vigilance: 'Espèce chère et lente : ne pas déranger',
    presentation: "Cubaris de Thaïlande dont la tête rappelle un petit canard en plastique, devenu un des cloportes les plus recherchés. Timide, il passe beaucoup de temps enroulé ou enterré. Une espèce de patience, à réserver aux éleveurs déjà à l'aise.",
    habitat: "Substrat profond (8-10 cm) riche en feuilles décomposées et bois pourri, mousse vivante, écorces et feuilles de catappa (qui gardent un pH correct). Humidité élevée mais aération indispensable : un bac humide et confiné leur est fatal, surtout au chaud. Garder un coin plus sec.",
    feeding_detail: "Feuilles mortes, bois pourri, mousse, champignons, un peu de légumes et de protéines. Retirer les restes avant qu'ils ne moisissent.",
    repro_sexing: SEXING,
    repro_conditions: "Calme absolu, conditions stables pendant des mois, substrat renouvelé par petites touches quand un tiers devient du frass.",
    repro_mating: "Peu observé ; les femelles portent de petites portées.",
    repro_incubation: "Plusieurs semaines dans le marsupium.",
    repro_juveniles: "Peu de petits par portée, croissance lente : la colonie met longtemps à décoller.",
    repro_pitfalls: "Chaleur au-delà de 27 °C, manque d'aération, manipulations fréquentes, substrat épuisé jamais renouvelé.",
    lifespan: '2 à 3 ans (estimation)'
  },
  {
    category: 'cloporte', common_name: "Cloporte rugueux 'Dalmatian'", scientific_name: 'Porcellio scaber "Dalmatian"',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 18, temp_max: 26,
    sociability: 'Colonie nombreuse', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Forme blanche tachetée de noir du cloporte rugueux, l'espèce des jardins. Aussi robuste que la forme sauvage, il est très recherché pour son motif.",
    habitat: "Substrat de 5 cm (terreau, fibre de coco, bois pourri), feuilles mortes, écorces. Un côté humide, un côté sec, bonne aération : il supporte des conditions plus sèches que la plupart des cloportes.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes (carotte, courgette), protéines une fois par semaine, calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Se reproduit facilement à température ambiante.",
    repro_mating: "Accouplements toute l'année, femelles portantes visibles à leur ventre blanchâtre.",
    repro_incubation: "Environ 3 à 6 semaines dans le marsupium selon la chaleur.",
    repro_juveniles: "Adultes en 3 à 4 mois. Garder les plus beaux motifs pour fixer la forme.",
    repro_pitfalls: "Mélanger avec d'autres formes de P. scaber (le motif se perd), bac détrempé et sans aération.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'cloporte', common_name: "Cloporte géant 'Milkback'", scientific_name: 'Porcellio laevis "Milkback"',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 20, temp_max: 28,
    sociability: 'Colonie nombreuse', diet_summary: 'Détritivore vorace, aime les protéines',
    vigilance: 'Peut grignoter des animaux en mue',
    presentation: "Forme de Porcellio laevis au dos crème et aux flancs gris, rapide et très prolifique comme les autres formes de l'espèce (Orange, Dairy Cow...). Excellent cloporte de vente et de nettoyage.",
    habitat: "Substrat de 5 cm plutôt aéré, un côté humide et un côté sec, écorces et feuilles. Bonne aération : il préfère un bac sain à un bac détrempé.",
    feeding_detail: "Très vorace : feuilles, bois, légumes, et beaucoup de protéines (granulés pour poissons, crevettes séchées) sinon il devient cannibale. Calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur (24-27 °C) et protéines : la population explose.",
    repro_mating: "Accouplements toute l'année.",
    repro_incubation: "3 à 5 semaines dans le marsupium.",
    repro_juveniles: "Croissance très rapide, adultes en 2 à 3 mois.",
    repro_pitfalls: "Manque de protéines (cannibalisme), surpopulation, mélange avec d'autres formes de laevis.",
    lifespan: '1 à 2 ans', feed_every_days: 3
  },
  {
    category: 'cloporte', common_name: "Cloporte dilaté 'Giant Canyon'", scientific_name: 'Porcellio dilatatus "Giant Canyon"',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 18, temp_max: 25,
    sociability: 'Colonie calme', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Forme géante de Porcellio dilatatus, large et lente, qui dépasse 2 cm. Calme et peu craintive, elle est agréable à observer.",
    habitat: "Substrat de 5 à 8 cm humide, feuilles mortes, bois pourri et écorces. Plus humide que la plupart des Porcellio, mais avec un coin plus sec et une bonne aération.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes, protéines chaque semaine, calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Température modérée et humidité stable.",
    repro_mating: "Accouplements surtout aux beaux jours.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Croissance moyenne, adultes en 4 à 6 mois.",
    repro_pitfalls: "Chaleur excessive, bac trop sec.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'cloporte', common_name: 'Cloporte géant de Hoffmannsegg', scientific_name: 'Porcellio hoffmannseggi',
    difficulty: 3, humidity_min: 50, humidity_max: 65, temp_min: 20, temp_max: 28,
    sociability: 'Colonie, mères protectrices', diet_summary: 'Détritivore, gros besoins en protéines',
    vigilance: 'Mordille les animaux en mue',
    presentation: "Le plus grand Porcellio (3 à 4 cm), originaire d'Espagne et du Portugal. Les mères gardent et protègent leurs petits, un comportement rare chez les cloportes. Espèce spectaculaire mais lente.",
    habitat: "Bac bien aéré avec un substrat majoritairement sec (terre, sable, feuilles) et une zone humide sous écorce. Beaucoup de cachettes en liège : les adultes sont territoriaux.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes, et des protéines plusieurs fois par semaine. Calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur estivale, protéines abondantes et une période plus fraîche en hiver pour relancer la reproduction.",
    repro_mating: "Accouplements au printemps et en été.",
    repro_incubation: "Environ 6 semaines dans le marsupium.",
    repro_juveniles: "La mère garde ses petits quelques jours. Croissance lente : près d'un an pour atteindre la taille adulte.",
    repro_pitfalls: "Bac trop humide et confiné, manque de protéines, trop peu de cachettes.",
    lifespan: '3 à 4 ans', size_class: 'moyen', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: 'Cloporte large d\'Espagne', scientific_name: 'Porcellio expansus',
    difficulty: 3, humidity_min: 50, humidity_max: 65, temp_min: 20, temp_max: 28,
    sociability: 'Colonie', diet_summary: 'Détritivore, aime les protéines',
    vigilance: 'Aucune',
    presentation: "Grand cloporte plat et large du sud de l'Espagne, aux bords jaune orangé. Lent à s'établir, il impressionne par sa forme très étalée.",
    habitat: "Installation sèche et bien aérée : terre sablonneuse, feuilles, écorces, avec une seule zone humide. Craint l'humidité stagnante.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes et protéines régulières, calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, aération, et une saison plus fraîche l'hiver.",
    repro_mating: "Accouplements au printemps.",
    repro_incubation: "Environ 6 semaines dans le marsupium.",
    repro_juveniles: "Petites portées, croissance lente.",
    repro_pitfalls: "Bac humide et confiné, manque de cachettes plates.",
    lifespan: '2 à 4 ans (estimation)', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: "Cloporte orné 'High Yellow'", scientific_name: 'Porcellio ornatus "High Yellow"',
    difficulty: 2, humidity_min: 50, humidity_max: 65, temp_min: 20, temp_max: 27,
    sociability: 'Colonie', diet_summary: 'Détritivore, aime les protéines',
    vigilance: 'Aucune',
    presentation: "Porcellio d'Espagne de 2 à 2,5 cm, sélectionné pour ses taches jaune vif sur fond sombre. Actif et assez prolifique une fois installé.",
    habitat: "Substrat sec et aéré avec un coin humide, écorces, feuilles. Comme les autres Porcellio espagnols, il préfère le sec à l'humide.",
    feeding_detail: "Feuilles, bois pourri, légumes, protéines chaque semaine, calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur et protéines, aération.",
    repro_mating: "Accouplements surtout du printemps à l'automne.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Adultes en 5 à 6 mois. Sélectionner les plus jaunes pour garder la forme.",
    repro_pitfalls: "Bac trop humide, manque de protéines.",
    lifespan: '2 à 3 ans', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: 'Cloporte de Werner', scientific_name: 'Porcellio werneri',
    difficulty: 2, humidity_min: 55, humidity_max: 70, temp_min: 20, temp_max: 26,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, protéines',
    vigilance: 'Aucune',
    presentation: "Porcellio de Grèce, noir semé de taches blanches. Moins courant que les espèces espagnoles, il attire par son contraste.",
    habitat: "Substrat plutôt sec et aéré, une zone humide, écorces et feuilles.",
    feeding_detail: "Feuilles mortes, bois, légumes, protéines chaque semaine, calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Conditions stables, chaleur modérée.",
    repro_mating: "Accouplements aux beaux jours.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Croissance moyenne.",
    repro_pitfalls: "Bac détrempé, aération insuffisante.",
    lifespan: '2 à 3 ans (estimation)', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: "Cloporte poudré 'Orange Cream'", scientific_name: 'Porcellionides pruinosus "Orange Cream"',
    difficulty: 1, humidity_min: 60, humidity_max: 80, temp_min: 20, temp_max: 30,
    sociability: 'Colonie très nombreuse', diet_summary: 'Détritivore : tout ce qui se décompose',
    vigilance: 'Aucune',
    presentation: "Petit cloporte très rapide, orange pâle et poudré. Le plus prolifique de tous : idéal comme équipe de nettoyage ou comme nourriture vivante.",
    habitat: "Substrat de 3 à 5 cm, feuilles et écorces, un côté humide. Supporte la chaleur.",
    feeding_detail: "Feuilles, bois, légumes, restes de nourriture, protéines.",
    repro_sexing: SEXING,
    repro_conditions: "Se reproduit sans aucune aide dès 22 °C.",
    repro_mating: "Accouplements permanents.",
    repro_incubation: "3 à 4 semaines dans le marsupium.",
    repro_juveniles: "Adultes en 2 mois environ.",
    repro_pitfalls: "Il envahit tout bac où il s'échappe : ne pas le mettre avec une espèce lente à garder pure.",
    lifespan: '1 à 2 ans'
  },
  {
    category: 'cloporte', common_name: "Cloporte maculé 'Zebra'", scientific_name: 'Armadillidium maculatum "Zebra"',
    difficulty: 2, humidity_min: 55, humidity_max: 70, temp_min: 18, temp_max: 26,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Cloporte boule de Provence, rayé de noir et de blanc comme un zèbre. Une espèce de France, robuste, qui se roule en boule parfaite.",
    habitat: "Substrat calcaire (terre, sable, coquilles broyées), feuilles et écorces. Plutôt sec et aéré, avec une zone humide.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes, protéines, beaucoup de calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Calcium abondant et une saison plus fraîche en hiver.",
    repro_mating: "Accouplements au printemps et en été.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Les rayures apparaissent au fil des mues ; adultes en 6 mois environ.",
    repro_pitfalls: "Bac trop humide, manque de calcium.",
    lifespan: '2 à 3 ans', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: "Cloporte de Klug 'Montenegro'", scientific_name: 'Armadillidium klugii "Montenegro"',
    difficulty: 3, humidity_min: 55, humidity_max: 70, temp_min: 18, temp_max: 25,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Cloporte boule de la côte adriatique (Monténégro, Croatie), noir taché de rouge, d'orange et de jaune comme un clown. Une des plus belles espèces d'Armadillidium, plus lente à élever.",
    habitat: "Substrat calcaire bien drainé, pierres, écorces et feuilles. Plutôt sec avec une zone humide, bonne aération.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes, protéines, calcium abondant.",
    repro_sexing: SEXING,
    repro_conditions: "Une période plus fraîche en hiver (15-18 °C) aide à relancer les portées au printemps.",
    repro_mating: "Accouplements au printemps.",
    repro_incubation: "Environ 6 semaines dans le marsupium.",
    repro_juveniles: "Croissance lente ; les couleurs se révèlent en grandissant.",
    repro_pitfalls: "Chaleur continue, bac confiné et humide.",
    lifespan: '2 à 3 ans (estimation)', substrate_type: 'sec'
  },
  {
    category: 'cloporte', common_name: "Cloporte nasique 'Peach'", scientific_name: 'Armadillidium nasatum "Peach"',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 18, temp_max: 26,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Forme couleur pêche d'Armadillidium nasatum, un cloporte boule facile qui se roule moins parfaitement que A. vulgare. Bonne espèce de débutant.",
    habitat: "Substrat de 5 cm, feuilles, écorces, un côté humide et un côté plus sec.",
    feeding_detail: "Feuilles mortes, bois, légumes, protéines chaque semaine, calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Se reproduit facilement à température ambiante.",
    repro_mating: "Accouplements toute l'année.",
    repro_incubation: "4 à 5 semaines dans le marsupium.",
    repro_juveniles: "Adultes en 4 à 5 mois.",
    repro_pitfalls: "Mélange avec d'autres formes, manque de calcium.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'cloporte', common_name: "Cloporte commun 'Magic Potion'", scientific_name: 'Armadillidium vulgare "Magic Potion"',
    difficulty: 1, humidity_min: 60, humidity_max: 75, temp_min: 18, temp_max: 26,
    sociability: 'Colonie', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Forme du cloporte commun aux reflets violets, orange et blancs mêlés. Aussi facile que la forme sauvage, avec des couleurs qui varient d'un individu à l'autre.",
    habitat: "Substrat calcaire de 5 cm, feuilles et écorces, un côté humide.",
    feeding_detail: "Feuilles mortes, bois, légumes, protéines, calcium abondant.",
    repro_sexing: SEXING,
    repro_conditions: "Facile ; une saison plus fraîche en hiver aide.",
    repro_mating: "Accouplements du printemps à l'automne.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Adultes en 4 à 6 mois. Sélectionner les plus colorés.",
    repro_pitfalls: "Mélange avec d'autres formes de A. vulgare.",
    lifespan: '2 à 3 ans, parfois plus'
  },
  {
    category: 'cloporte', common_name: "Cloporte des murs 'Orange'", scientific_name: 'Oniscus asellus "Orange"',
    difficulty: 1, humidity_min: 75, humidity_max: 90, temp_min: 14, temp_max: 22,
    sociability: 'Colonie', diet_summary: 'Détritivore : bois pourri surtout',
    vigilance: 'Craint la chaleur',
    presentation: "Forme orange du grand cloporte plat des murs et des souches, très commun en France. Il aime le frais et le bois pourri.",
    habitat: "Substrat humide riche en bois pourri, écorces, feuilles. Frais (en dessous de 22 °C) et humide.",
    feeding_detail: "Bois pourri, feuilles, légumes, protéines.",
    repro_sexing: SEXING,
    repro_conditions: "Fraîcheur et humidité, bois pourri en abondance.",
    repro_mating: "Accouplements au printemps et en été.",
    repro_incubation: "4 à 6 semaines dans le marsupium.",
    repro_juveniles: "Croissance moyenne.",
    repro_pitfalls: "Chaleur d'été, bac qui sèche.",
    lifespan: '2 à 3 ans'
  },
  {
    category: 'cloporte', common_name: 'Cloporte blanc nain', scientific_name: 'Trichorhina tomentosa',
    difficulty: 1, humidity_min: 80, humidity_max: 95, temp_min: 20, temp_max: 28,
    sociability: 'Colonie très nombreuse', diet_summary: 'Détritivore : moisissures, restes, feuilles',
    vigilance: 'Aucune',
    presentation: "Minuscule cloporte blanc (4 à 5 mm) des tropiques, qui se reproduit sans mâle. Il vit dans le substrat et le nettoie : l'équipe de nettoyage idéale des terrariums humides.",
    habitat: "Substrat très humide et riche, mousse, bois pourri. Il reste presque toujours enterré.",
    feeding_detail: "Restes, moisissures, feuilles décomposées, un peu de levure ou de flocons.",
    repro_sexing: "Inutile : presque toutes les populations sont des femelles qui se reproduisent seules.",
    repro_conditions: "Humidité élevée et chaleur : la colonie s'installe seule.",
    repro_mating: "Pas d'accouplement (parthénogenèse).",
    repro_incubation: "Quelques semaines dans le marsupium.",
    repro_juveniles: "Adultes en 2 à 3 mois.",
    repro_pitfalls: "Substrat qui sèche.",
    lifespan: '1 à 2 ans', size_class: 'petit', niche: 'fouisseur'
  }
];
