module.exports = [
  {
    category: 'coleoptere', common_name: 'Scarabée Hercule', scientific_name: 'Dynastes hercules',
    difficulty: 4, humidity_min: 65, humidity_max: 80, temp_min: 20, temp_max: 25,
    sociability: 'Larves isolées ; un mâle par bac', diet_summary: 'Adultes : fruits ; larves : flake soil et bois pourri',
    vigilance: 'Larves longues à élever, grandes boîtes',
    presentation: "Le plus long scarabée du monde : jusqu'à 17 cm avec sa corne pour les plus grands mâles, élytres olive tachés de noir. La larve passe 1 an et demi à 2 ans dans le substrat : un élevage de patience et d'espace.",
    habitat: "Bac de ponte avec 25 cm de flake soil tassé au fond et bois pourri. Chaque grosse larve dans une boîte de 10 à 20 litres de flake soil. Adultes dans un bac aéré avec branches et écorces.",
    feeding_detail: "Adultes : banane, gelée pour coléoptères. Larves : flake soil riche et bois blanc pourri, renouvelés quand le substrat devient des crottes.",
    repro_sexing: "Le mâle porte deux longues cornes (tête et thorax) ; la femelle n'en a pas et a des élytres plus rugueux.",
    repro_conditions: "Température stable de 20 à 24 °C, substrat de très bonne qualité.",
    repro_mating: "La femelle pond dans le fond tassé du substrat.",
    repro_incubation: "Environ 1 mois.",
    repro_juveniles: "Trois stades larvaires sur 1 an et demi à 2 ans, la larve dépassant 100 g. Nymphose dans une loge qu'il ne faut pas casser.",
    repro_pitfalls: "Boîtes trop petites (adultes chétifs), chaleur excessive, loge de nymphose cassée.",
    lifespan: '2 ans et demi à 3 ans en tout, dont 6 mois à 1 an en adulte', size_class: 'grand'
  },
  {
    category: 'coleoptere', common_name: 'Scarabée rhinocéros du Japon', scientific_name: 'Trypoxylus dichotomus',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 20, temp_max: 26,
    sociability: 'Larves en groupe possibles', diet_summary: 'Adultes : fruits ; larves : flake soil',
    vigilance: 'Aucune',
    presentation: "Le kabutomushi japonais (4 à 8 cm), brun-rouge à noir, aux mâles armés d'une grande corne fourchue. Cycle court pour un scarabée rhinocéros : environ un an.",
    habitat: "Bac de ponte avec 20 cm de flake soil tassé au fond. Larves en groupe dans un grand bac ou en boîtes de 2 à 3 litres.",
    feeding_detail: "Adultes : fruits, gelée pour coléoptères. Larves : flake soil et bois pourri.",
    repro_sexing: "Mâle : longue corne fourchue sur la tête ; femelle sans corne.",
    repro_conditions: "Température douce, substrat riche.",
    repro_mating: "Ponte dans le substrat tassé.",
    repro_incubation: "2 à 3 semaines.",
    repro_juveniles: "Larves en 8 à 10 mois, nymphose verticale dans une loge.",
    repro_pitfalls: "Substrat pauvre, loge dérangée.",
    lifespan: 'environ 1 an, dont 2 à 3 mois en adulte'
  },
  {
    category: 'coleoptere', common_name: 'Scarabée rhinocéros siamois', scientific_name: 'Xylotrupes gideon',
    difficulty: 2, humidity_min: 60, humidity_max: 75, temp_min: 22, temp_max: 28,
    sociability: 'Mâles batailleurs', diet_summary: 'Adultes : fruits ; larves : flake soil',
    vigilance: 'Mâles agressifs entre eux',
    presentation: "Scarabée rhinocéros d'Asie du Sud-Est (4 à 6 cm), brun luisant, aux mâles à deux cornes en pince. Facile et rapide.",
    habitat: "Flake soil profond et bois pourri pour la ponte, branches pour les adultes.",
    feeding_detail: "Adultes : fruits, gelée. Larves : flake soil, bois pourri.",
    repro_sexing: "Mâle : cornes sur la tête et le thorax ; femelle sans corne.",
    repro_conditions: "Chaleur, substrat riche.",
    repro_mating: "Ponte dans le substrat.",
    repro_incubation: "2 à 3 semaines.",
    repro_juveniles: "Cycle en 6 à 8 mois.",
    repro_pitfalls: "Plusieurs mâles ensemble, substrat pauvre.",
    lifespan: 'environ 1 an, dont 2 à 4 mois en adulte'
  },
  {
    category: 'coleoptere', common_name: 'Lucane titan', scientific_name: 'Dorcus titanus',
    difficulty: 3, humidity_min: 60, humidity_max: 75, temp_min: 18, temp_max: 25,
    sociability: 'Couples séparés hors accouplement', diet_summary: 'Adultes : gelée, fruits ; larves : bois pourri',
    vigilance: 'Mâles qui pincent fort',
    presentation: "Grand lucane d'Asie (jusqu'à 10 cm pour les mâles), noir brillant aux longues mandibules. Les adultes vivent longtemps, parfois plusieurs années.",
    habitat: "Pour la ponte : bûches de bois blanc pourri enterrées dans du flake soil. Larves dans des bouteilles de bois fermenté ou de champignon (ou du bois pourri émietté). Adultes dans un bac aéré.",
    feeding_detail: "Adultes : gelée pour coléoptères, fruits. Larves : bois blanc pourri, rien d'autre.",
    repro_sexing: "Le mâle a de grandes mandibules ; la femelle de petites, larges et pointues.",
    repro_conditions: "Bois de ponte de qualité, température modérée.",
    repro_mating: "La femelle creuse le bois pour pondre ; retirer le mâle après l'accouplement (il peut la blesser).",
    repro_incubation: "Environ 3 semaines.",
    repro_juveniles: "Larves 8 mois à 1 an dans le bois pourri.",
    repro_pitfalls: "Mâle laissé avec la femelle, bois trop sec ou trop dur.",
    lifespan: '1 à 3 ans en adulte', diet_type: 'detritivore', substrate_type: 'flake'
  },
  {
    category: 'coleoptere', common_name: 'Ténébrion bleu', scientific_name: 'Asbolus verrucosus',
    difficulty: 3, humidity_min: 30, humidity_max: 50, temp_min: 22, temp_max: 30,
    sociability: 'Groupe', diet_summary: 'Omnivore : fruits, légumes, croquettes',
    vigilance: 'Aucune',
    presentation: "Le ténébrion « qui fait le mort » des déserts américains, bleu poudré et couvert de bosses. Très facile à garder et à manipuler, il peut vivre près de 10 ans ; le reproduire est plus délicat.",
    habitat: "Sable ou mélange sable et terre sec, 8 à 10 cm, avec un coin légèrement humide au fond. Écorces et pierres plates. Bonne aération.",
    feeding_detail: "Fruits, légumes, flocons, croquettes ; une feuille de salade donne l'eau dont il a besoin.",
    repro_sexing: "Difficile à l'œil : la femelle est souvent un peu plus grande et plus ronde.",
    repro_conditions: "Une couche de sable humide au fond, chaleur, et une période plus fraîche en hiver.",
    repro_mating: "Ponte dans le sable humide du fond.",
    repro_incubation: "Quelques semaines.",
    repro_juveniles: "Les larves vivent dans le sable humide ; croissance lente.",
    repro_pitfalls: "Bac entièrement humide (l'adulte n'aime pas), sable entièrement sec (pas de ponte).",
    lifespan: "jusqu'à 8 à 10 ans", diet_type: 'omnivore', size_class: 'moyen', niche: 'surface', substrate_type: 'sec'
  },
  {
    category: 'coleoptere', common_name: 'Ténébrion géant (Zophobas)', scientific_name: 'Zophobas atratus',
    difficulty: 1, humidity_min: 40, humidity_max: 60, temp_min: 24, temp_max: 30,
    sociability: 'Groupe', diet_summary: 'Omnivore : son, légumes, croquettes',
    vigilance: 'Larves qui pincent un peu',
    presentation: "Le « super ver » de la nourriture vivante (larves de 5 à 6 cm). Simple à reproduire pour nourrir ses prédateurs.",
    habitat: "Bac lisse avec son de blé ou flocons d'avoine et morceaux d'écorce. Les adultes noirs pondent dans le substrat.",
    feeding_detail: "Son, flocons, légumes (carotte), croquettes.",
    repro_sexing: "Difficile à l'œil.",
    repro_conditions: "Chaleur ; pour la nymphose, chaque larve doit être seule.",
    repro_mating: "Les adultes pondent dans le substrat ou dans les fissures d'écorce.",
    repro_incubation: "Environ 1 à 2 semaines.",
    repro_juveniles: "Les larves ne se nymphosent pas en groupe : les isoler 1 à 2 semaines dans de petits pots pour obtenir des adultes.",
    repro_pitfalls: "Larves jamais isolées (pas d'adultes), humidité excessive.",
    lifespan: 'environ 1 an', diet_type: 'omnivore', size_class: 'moyen', niche: 'fouisseur', substrate_type: 'sec', feed_every_days: 3
  },
  {
    category: 'coleoptere', common_name: 'Ténébrion meunier (vers de farine)', scientific_name: 'Tenebrio molitor',
    difficulty: 1, humidity_min: 40, humidity_max: 60, temp_min: 20, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Omnivore : son, légumes',
    vigilance: 'Aucune',
    presentation: "Le ver de farine classique : facile, sans odeur, une nourriture vivante de base pour les petits prédateurs.",
    habitat: "Bac lisse avec son de blé ou flocons d'avoine, morceaux de carotte pour l'eau.",
    feeding_detail: "Son, flocons, carotte, pomme de terre.",
    repro_sexing: "Difficile à l'œil.",
    repro_conditions: "Chaleur (25-27 °C).",
    repro_mating: "Ponte dans le son.",
    repro_incubation: "1 à 2 semaines.",
    repro_juveniles: "Cycle complet en 3 à 4 mois.",
    repro_pitfalls: "Légumes qui moisissent, acariens dans un son trop humide.",
    lifespan: 'quelques mois', diet_type: 'omnivore', size_class: 'petit', niche: 'fouisseur', substrate_type: 'sec', feed_every_days: 4
  }
];
