module.exports = [
  {
    category: 'crabe', common_name: 'Crabe vampire violet', scientific_name: 'Geosesarma dennerle',
    difficulty: 2, humidity_min: 75, humidity_max: 90, temp_min: 22, temp_max: 26,
    sociability: 'Groupe (plus de femelles que de mâles)', diet_summary: 'Opportuniste : petits insectes, légumes, granulés',
    vigilance: 'Grimpe partout : couvercle étanche',
    presentation: "Petit crabe d'Indonésie (carapace de 2 cm), violet aux yeux jaunes, le plus courant des « crabes vampires ». Il se reproduit en eau douce : les petits naissent déjà crabes.",
    habitat: "Paludarium : deux tiers de terre (fibre de coco, mousse, racines) et un tiers d'eau douce peu profonde (3 à 5 cm) avec des pierres pour remonter. Couvercle sans aucun jour : ils passent par la moindre fente.",
    feeding_detail: "Petits insectes (drosophiles, grillons), granulés pour crevettes ou poissons, légumes, feuilles de catappa.",
    repro_sexing: "Le mâle a l'abdomen étroit et pointu, des pinces plus grosses ; la femelle a un abdomen large et arrondi.",
    repro_conditions: "Un groupe avec plus de femelles, beaucoup de cachettes, eau propre.",
    repro_mating: "La femelle porte ses œufs sous l'abdomen.",
    repro_incubation: "Environ 4 semaines sous la femelle.",
    repro_juveniles: "Les petits crabes sortent directement de l'abdomen de la mère. Les séparer des adultes qui peuvent les manger.",
    repro_pitfalls: "Fuites, eau sale, trop de mâles (combats).",
    lifespan: '2 à 3 ans', size_class: 'petit'
  },
  {
    category: 'crabe', common_name: 'Crabe vampire rouge', scientific_name: 'Geosesarma hagen',
    difficulty: 2, humidity_min: 75, humidity_max: 90, temp_min: 22, temp_max: 26,
    sociability: 'Groupe', diet_summary: 'Opportuniste : petits insectes, granulés, légumes',
    vigilance: 'Grimpe partout : couvercle étanche',
    presentation: "Le « red devil » : petit crabe d'Indonésie au corps rouge et noir et aux yeux jaunes. Même élevage que le crabe vampire violet.",
    habitat: "Paludarium avec terre, mousse et eau douce peu profonde ; couvercle parfaitement fermé.",
    feeding_detail: "Petits insectes, granulés, légumes, catappa.",
    repro_sexing: "Abdomen étroit chez le mâle, large chez la femelle.",
    repro_conditions: "Groupe à majorité de femelles, cachettes.",
    repro_mating: "Œufs portés sous l'abdomen de la femelle.",
    repro_incubation: "Environ 4 semaines.",
    repro_juveniles: "Petits crabes complets à la naissance ; à séparer.",
    repro_pitfalls: "Fuites, combats entre mâles.",
    lifespan: '2 à 3 ans', size_class: 'petit'
  },
  {
    category: 'crabe', common_name: 'Crabe à pinces rouges', scientific_name: 'Perisesarma bidens',
    difficulty: 3, humidity_min: 75, humidity_max: 90, temp_min: 22, temp_max: 28,
    sociability: 'Groupe avec beaucoup de place', diet_summary: 'Opportuniste : granulés, légumes, insectes',
    vigilance: 'Il lui faut de l’eau saumâtre',
    presentation: "Crabe des mangroves d'Asie (carapace de 4 cm) aux pinces rouge vif, souvent vendu à tort comme crabe d'eau douce. Il a besoin d'eau légèrement salée.",
    habitat: "Paludarium avec une grande partie terrestre et de l'eau saumâtre (sel marin, densité d'environ 1,005 à 1,010). Couvercle fermé.",
    feeding_detail: "Granulés pour crustacés, légumes, insectes, poisson.",
    repro_sexing: "Abdomen étroit chez le mâle, large chez la femelle.",
    repro_conditions: "Reproduction quasi impossible en captivité.",
    repro_mating: "Les femelles peuvent porter des œufs.",
    repro_incubation: "Les larves éclosent dans l'eau et ont besoin d'eau de mer : elles meurent en terrarium.",
    repro_juveniles: "Les animaux vendus sont capturés dans la nature.",
    repro_pitfalls: "Eau douce seulement (mortalité), bac trop petit, fuites.",
    lifespan: '2 à 4 ans'
  },
  {
    category: 'crabe', common_name: 'Crabe arc-en-ciel', scientific_name: 'Cardisoma armatum',
    difficulty: 3, humidity_min: 70, humidity_max: 85, temp_min: 24, temp_max: 28,
    sociability: 'Solitaire', diet_summary: 'Opportuniste : légumes, fruits, poisson, insectes',
    vigilance: 'Pinces puissantes, s’enterre et s’évade',
    presentation: "Grand crabe terrestre d'Afrique de l'Ouest (carapace de 6 cm, pattes comprises 15 cm et plus), bleu, violet et orange. Il creuse des terriers et défend son territoire.",
    habitat: "Grand bac avec 15 à 20 cm de substrat humide qui tient les terriers (sable et terre), un bassin d'eau douce et un d'eau saumâtre où il peut s'immerger. Couvercle lourd.",
    feeding_detail: "Légumes, fruits, poisson, crevettes, insectes, feuilles ; calcium (os de seiche).",
    repro_sexing: "Abdomen étroit en triangle chez le mâle, large chez la femelle.",
    repro_conditions: "Pas de reproduction en captivité.",
    repro_mating: "Les larves ont besoin de la mer.",
    repro_incubation: "Non applicable en terrarium.",
    repro_juveniles: "Animaux issus de la nature.",
    repro_pitfalls: "Plusieurs individus ensemble (combats), substrat trop mince pour creuser, pas d'eau saumâtre.",
    lifespan: '8 à 10 ans (estimation)', size_class: 'grand', diet_type: 'opportuniste', niche: 'fouisseur'
  },
  {
    category: 'crabe', common_name: 'Bernard-l’ermite terrestre des Caraïbes', scientific_name: 'Coenobita clypeatus',
    difficulty: 3, humidity_min: 70, humidity_max: 85, temp_min: 24, temp_max: 28,
    sociability: 'En groupe obligatoirement', diet_summary: 'Opportuniste : fruits, légumes, protéines',
    vigilance: 'Coquilles de rechange indispensables',
    presentation: "Bernard-l'ermite des Caraïbes qui vit sur terre et change de coquille en grandissant. Très sociable, il vit longtemps si l'installation est bonne.",
    habitat: "Grand bac avec 15 cm (ou 6 fois la hauteur du plus gros) de sable et fibre de coco humides pour s'enterrer à la mue, deux bassins assez profonds pour s'immerger : eau douce déchlorée et eau de mer (sel marin). Plusieurs coquilles vides un peu plus grandes que les leurs.",
    feeding_detail: "Fruits, légumes, noix, poisson, crevettes séchées, coquilles d'œuf broyées. Varier beaucoup.",
    repro_sexing: "Difficile : la femelle a deux petits orifices (gonopores) à la base de la troisième paire de pattes, visibles seulement quand l'animal sort bien de sa coquille.",
    repro_conditions: "Pas de reproduction en terrarium.",
    repro_mating: "Les larves se développent en mer.",
    repro_incubation: "Non applicable en terrarium.",
    repro_juveniles: "Animaux issus de la nature.",
    repro_pitfalls: "Le déranger pendant la mue (enterré plusieurs semaines), sel de table, pas de coquilles de rechange, élevage seul.",
    lifespan: '10 à 20 ans et plus en bonnes conditions'
  }
];
