const SEXING = "Hermaphrodite : chaque escargot est à la fois mâle et femelle. Deux adultes suffisent, et un seul peut parfois pondre après un ancien accouplement.";

module.exports = [
  {
    category: 'escargot', common_name: 'Achatine tigrée', scientific_name: 'Achatina achatina',
    difficulty: 3, humidity_min: 75, humidity_max: 90, temp_min: 25, temp_max: 29,
    sociability: 'Petit groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Craint le froid ; se laver les mains',
    presentation: "Le plus grand escargot terrestre (coquille jusqu'à 20 cm), à la coquille rayée de brun et de jaune comme un tigre. Plus frileux et plus lent que l'achatine commune.",
    habitat: "Grand bac (80 cm pour un adulte) avec 10 à 15 cm de terreau sans engrais ou de fibre de coco humide, de quoi s'enterrer. Chaleur constante, humidité élevée et bonne aération.",
    feeding_detail: "Légumes variés (courgette, concombre, salade foncée, patate douce), fruits, et du calcium en permanence (os de seiche, carbonate de calcium). Une source de protéines de temps en temps.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur stable (au moins 26 °C), escargots adultes et bien nourris.",
    repro_mating: "Accouplement réciproque, puis ponte enterrée dans le substrat.",
    repro_incubation: "Quelques semaines dans le substrat chaud.",
    repro_juveniles: "Les petits mangent d'abord leur coquille d'œuf ; croissance lente, maturité en 2 à 3 ans.",
    repro_pitfalls: "Froid (inactivité, refus de manger), manque de calcium (coquille fine), bac détrempé.",
    lifespan: '5 à 10 ans', size_class: 'grand'
  },
  {
    category: 'escargot', common_name: 'Achatine bordée', scientific_name: 'Archachatina marginata',
    difficulty: 2, humidity_min: 75, humidity_max: 90, temp_min: 24, temp_max: 28,
    sociability: 'Petit groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Se laver les mains',
    presentation: "Grand escargot d'Afrique de l'Ouest (coquille de 15 à 20 cm), calme, au bord de coquille rose ou blanc. Il pond peu d'œufs, mais de très gros.",
    habitat: "Grand bac, 10 cm de terreau sans engrais humide, écorces. Chaleur et humidité stables.",
    feeding_detail: "Légumes, fruits, feuilles, calcium en permanence, protéines de temps en temps.",
    repro_sexing: SEXING,
    repro_conditions: "Adultes bien nourris, chaleur.",
    repro_mating: "Accouplement réciproque ; ponte de quelques gros œufs (taille d'un petit œuf d'oiseau) dans le substrat.",
    repro_incubation: "Environ 1 à 2 mois.",
    repro_juveniles: "Les petits sont déjà gros à l'éclosion ; maturité en 1 an et demi à 2 ans.",
    repro_pitfalls: "Froid, manque de calcium, substrat qui sèche.",
    lifespan: "jusqu'à 10 ans", size_class: 'grand'
  },
  {
    category: 'escargot', common_name: 'Achatine immaculée', scientific_name: 'Lissachatina immaculata',
    difficulty: 1, humidity_min: 70, humidity_max: 90, temp_min: 22, temp_max: 27,
    sociability: 'Groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Se laver les mains',
    presentation: "Achatine d'Afrique de l'Est (12 cm environ), à la coquille brun clair et au bord rose. Robuste et prolifique.",
    habitat: "Bac moyen à grand, terreau sans engrais humide, écorces.",
    feeding_detail: "Légumes, fruits, calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Facile dès que les adultes sont bien nourris.",
    repro_mating: "Pontes enterrées de plusieurs dizaines à centaines d'œufs.",
    repro_incubation: "2 à 3 semaines.",
    repro_juveniles: "Croissance rapide ; maturité en moins d'un an.",
    repro_pitfalls: "Pontes non contrôlées (trop de petits) : retirer les œufs en trop.",
    lifespan: '5 ans environ', size_class: 'grand'
  },
  {
    category: 'escargot', common_name: 'Achatine réticulée', scientific_name: 'Lissachatina reticulata',
    difficulty: 2, humidity_min: 75, humidity_max: 90, temp_min: 24, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Se laver les mains',
    presentation: "Grande achatine de Tanzanie et Zanzibar (jusqu'à 18 cm), à la coquille finement réticulée. Curieuse et active.",
    habitat: "Grand bac, terreau sans engrais humide profond.",
    feeding_detail: "Légumes, fruits, calcium en continu, protéines de temps en temps.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur et nourriture abondante.",
    repro_mating: "Grosses pontes enterrées.",
    repro_incubation: "2 à 4 semaines.",
    repro_juveniles: "Croissance assez rapide, maturité vers 1 an.",
    repro_pitfalls: "Froid, manque de calcium.",
    lifespan: '5 à 7 ans', size_class: 'grand'
  },
  {
    category: 'escargot', common_name: 'Limicolaire flammée', scientific_name: 'Limicolaria flammea',
    difficulty: 1, humidity_min: 70, humidity_max: 90, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Se laver les mains',
    presentation: "Escargot d'Afrique de l'Ouest à coquille allongée (5 à 6 cm) striée de flammes brunes. Petit, prolifique et facile.",
    habitat: "Bac moyen, terreau sans engrais humide, mousse, écorces.",
    feeding_detail: "Légumes, fruits, calcium.",
    repro_sexing: SEXING,
    repro_conditions: "Facile.",
    repro_mating: "Pontes enterrées.",
    repro_incubation: "2 à 4 semaines.",
    repro_juveniles: "Maturité en quelques mois.",
    repro_pitfalls: "Surpopulation.",
    lifespan: '2 à 4 ans (estimation)', size_class: 'moyen'
  },
  {
    category: 'escargot', common_name: 'Petit-gris', scientific_name: 'Cornu aspersum',
    difficulty: 1, humidity_min: 70, humidity_max: 90, temp_min: 15, temp_max: 22,
    sociability: 'Groupe', diet_summary: 'Herbivore : légumes, calcium',
    vigilance: 'Craint la chaleur',
    presentation: "L'escargot de nos jardins (coquille de 3 à 4 cm). Il hiberne l'hiver et estive par temps sec : un élevage au rythme des saisons.",
    habitat: "Bac aéré, terreau sans engrais humide, mousse, à garder au frais (pas au-dessus de 24 °C).",
    feeding_detail: "Salade, courgette, carotte, feuilles d'orties, calcium en continu.",
    repro_sexing: SEXING,
    repro_conditions: "Un hiver au frais (hibernation) puis le printemps.",
    repro_mating: "Accouplement réciproque ; ponte d'environ 80 à 100 œufs dans un trou creusé dans le sol.",
    repro_incubation: "2 à 4 semaines.",
    repro_juveniles: "Maturité en 1 à 2 ans.",
    repro_pitfalls: "Chaleur, bac sale (les escargots sont sensibles aux bactéries).",
    lifespan: '2 à 5 ans', size_class: 'moyen'
  }
];
