module.exports = [
  {
    category: 'iule', common_name: 'Iule géant africain', scientific_name: 'Archispirostreptus gigas',
    difficulty: 2, humidity_min: 75, humidity_max: 85, temp_min: 24, temp_max: 28,
    sociability: 'Se garde en groupe sans souci', diet_summary: 'Détritivore : feuilles, bois pourri, légumes',
    vigilance: 'Sécrétion irritante si stressé — se laver les mains',
    presentation: "Le plus grand iule du monde : jusqu'à 25-30 cm pour les plus beaux adultes, d'un noir brun profond. Lent, calme et très facile à manipuler, c'est l'espèce vitrine des grands iules africains.",
    habitat: "Grand bac (au moins 60 cm de long pour un petit groupe) avec 15 cm de substrat meuble : terreau de feuilles, fibre de coco et bois blanc pourri émietté. Litière épaisse de feuilles de chêne ou de hêtre, écorces pour se cacher, calcium en continu (os de seiche, coquilles broyées).",
    feeding_detail: "Feuilles mortes et bois décomposé à volonté, qui forment la base. En complément : concombre, courgette, carotte, salade, fruits mûrs (banane, mangue), et un peu de protéines de temps en temps (granulés pour poissons).",
    repro_sexing: "Le mâle adulte n'a pas de pattes sur le 7e anneau : elles sont remplacées par les gonopodes, bien visibles en retournant l'animal. La femelle garde une rangée de pattes continue.",
    repro_conditions: "Un groupe adulte dans un bac ancien et stable, avec un substrat profond jamais sec et une nourriture abondante. La reproduction est régulière mais lente : il faut des années pour qu'un groupe devienne une vraie colonie.",
    repro_mating: "L'accouplement se fait ventre contre ventre, les deux iules enroulés l'un contre l'autre, parfois pendant des heures. La femelle pond ensuite des œufs dans de petites capsules de terre au fond du substrat.",
    repro_incubation: "Les œufs éclosent au bout de quelques semaines à trois mois, sans qu'on les voie : le meilleur est de laisser le substrat tranquille.",
    repro_juveniles: "Les petits, blancs puis grisâtres, ne mesurent que quelques millimètres. Ils grandissent par mues successives et mettent 3 à 5 ans à devenir adultes. Un substrat riche en bois pourri les aide beaucoup.",
    repro_pitfalls: "Fouiller le fond du bac, laisser le substrat sécher, oublier le calcium (mues ratées), un bac trop petit où le substrat s'épuise vite.",
    lifespan: '7 à 10 ans', size_class: 'grand'
  },
  {
    category: 'iule', common_name: 'Iule à pattes rouges du Kenya', scientific_name: 'Epibolus pulchripes',
    difficulty: 3, humidity_min: 70, humidity_max: 85, temp_min: 22, temp_max: 27,
    sociability: 'Grégaire', diet_summary: 'Détritivore : bois pourri surtout, feuilles',
    vigilance: 'Sécrétion qui tache la peau si stressé',
    presentation: "Iule d'Afrique de l'Est d'environ 10 cm, noir brillant avec des pattes rouge vif et des anneaux bordés de rouge. Robuste en adulte, il demande plus d'attention pour réussir les jeunes.",
    habitat: "Substrat de 12 à 15 cm, meuble et riche : terreau de feuilles, fibre de coco et beaucoup de bois blanc pourri. Une couche épaisse de feuilles mortes en surface, humidifiée régulièrement, et une bonne aération pour éviter l'air confiné.",
    feeding_detail: "Le bois blanc bien décomposé est l'aliment principal, surtout pour les jeunes. Feuilles mortes, légumes et fruits en complément, calcium disponible en permanence.",
    repro_sexing: "Gonopodes du mâle au 7e anneau, visibles sous l'animal ; la femelle a des pattes à cet endroit.",
    repro_conditions: "Substrat profond renouvelé par le dessous avec du bois pourri, humidité stable et aération correcte : c'est surtout l'air confiné et le substrat pauvre qui font perdre les jeunes.",
    repro_mating: "Accouplement ventre contre ventre ; la ponte se fait dans le substrat, dans de petites loges.",
    repro_incubation: "Éclosion en quelques semaines à deux mois dans le substrat, sans intervention.",
    repro_juveniles: "Les jeunes sont fragiles et se nourrissent presque uniquement de bois pourri et de substrat riche. Maturité en 2 à 3 ans.",
    repro_pitfalls: "Bac trop fermé (moisissures, air confiné), substrat pauvre en bois décomposé, sécheresse même courte : les juvéniles en meurent en premier.",
    lifespan: '5 à 7 ans (estimation)'
  },
  {
    category: 'iule', common_name: 'Iule corail', scientific_name: 'Trigoniulus corallinus',
    difficulty: 1, humidity_min: 70, humidity_max: 85, temp_min: 22, temp_max: 28,
    sociability: 'Très grégaire, colonie nombreuse', diet_summary: 'Détritivore : feuilles, bois, légumes',
    vigilance: 'Aucune',
    presentation: "Petit iule rouille de 5 à 7 cm venu d'Asie du Sud-Est, aujourd'hui présent dans toutes les régions tropicales. Très actif, prolifique et peu exigeant : une valeur sûre pour une première colonie ou pour la vente.",
    habitat: "Substrat de 8 à 10 cm (terreau de feuilles, fibre de coco), feuilles mortes, morceaux de bois tendre et écorces. Tolère bien de petites erreurs d'humidité tant qu'un coin reste humide.",
    feeding_detail: "Feuilles mortes, bois pourri, légumes et fruits variés, un peu de protéines de temps en temps. Calcium en continu.",
    repro_sexing: "Gonopodes du mâle visibles au 7e anneau en retournant l'animal.",
    repro_conditions: "Se reproduit tout seul dans un bac stable et bien nourri : il suffit de lui laisser de la place.",
    repro_mating: "Accouplements fréquents, ponte dans le substrat.",
    repro_incubation: "Quelques semaines dans le substrat.",
    repro_juveniles: "Croissance rapide pour un iule : adultes en 6 mois à 1 an. La colonie double vite.",
    repro_pitfalls: "Surpopulation dans un bac trop petit, substrat jamais renouvelé, manque de calcium.",
    lifespan: '2 à 4 ans', size_class: 'moyen'
  },
  {
    category: 'iule', common_name: 'Iule du désert', scientific_name: 'Orthoporus ornatus',
    difficulty: 3, humidity_min: 50, humidity_max: 65, temp_min: 24, temp_max: 30,
    sociability: 'Se garde en groupe', diet_summary: 'Détritivore : feuilles sèches, bois, légumes',
    vigilance: 'Sécrétion irritante si stressé',
    presentation: "Iule des déserts du sud des États-Unis et du Mexique, de 10 à 15 cm, aux anneaux brun-doré. Il vit en surface quand il pleut et s'enterre profondément le reste du temps : son installation est à l'opposé de celle des iules tropicaux.",
    habitat: "Substrat profond (15 cm) mêlant sable, terre et fibre de coco : sec en surface mais légèrement humide au fond, pour qu'il choisisse son niveau. Bonne aération, chaleur (point chaud vers 28-30 °C), écorces et feuilles sèches.",
    feeding_detail: "Feuilles mortes, bois décomposé, légumes (courgette, carotte) et fruits en petite quantité, calcium en continu. Nourrir après avoir humidifié un coin du bac, comme après une pluie.",
    repro_sexing: "Gonopodes du mâle au 7e anneau, visibles sous l'animal.",
    repro_conditions: "Reproduction rare en captivité. Les éleveurs qui réussissent simulent une saison des pluies : une période plus sèche, puis plusieurs semaines plus humides et plus chaudes.",
    repro_mating: "Accouplements pendant la période humide, ponte dans la couche humide du fond.",
    repro_incubation: "Peu documentée en captivité : laisser le substrat du fond intact plusieurs mois.",
    repro_juveniles: "Croissance lente ; les jeunes restent dans la couche humide.",
    repro_pitfalls: "L'installer comme un iule tropical (trop humide, il pourrit ou ne sort plus), un substrat entièrement sec, retourner le fond du bac.",
    lifespan: '7 à 10 ans (estimation)', substrate_type: 'sec'
  },
  {
    category: 'iule', common_name: 'Iule ivoire de Floride', scientific_name: 'Chicobolus spinigerus',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 21, temp_max: 26,
    sociability: 'Grégaire', diet_summary: 'Détritivore : feuilles, bois pourri, légumes',
    vigilance: 'Sécrétion irritante si stressé',
    presentation: "Iule de Floride de 8 à 10 cm, noir aux bords d'anneaux ivoire et pattes claires. Calme et robuste, il supporte des températures plus fraîches que les iules africains.",
    habitat: "Substrat de 10 cm (terreau de feuilles, fibre de coco, bois pourri), feuilles mortes de chêne en couche épaisse, écorces. Température ambiante d'intérieur suffisante.",
    feeding_detail: "Feuilles mortes et bois pourri à volonté, légumes et fruits en complément, calcium en continu.",
    repro_sexing: "Gonopodes du mâle au 7e anneau, visibles sous l'animal.",
    repro_conditions: "Bac stable, substrat profond et riche, humidité régulière. Se reproduit assez bien en captivité.",
    repro_mating: "Accouplement ventre contre ventre ; ponte dans des capsules de terre au fond du bac.",
    repro_incubation: "Éclosion en quelques semaines dans le substrat.",
    repro_juveniles: "Les jeunes grandissent dans le substrat profond ; maturité en 2 à 3 ans.",
    repro_pitfalls: "Substrat trop mince ou qui sèche, manque de bois pourri, manque de calcium.",
    lifespan: '5 à 7 ans (estimation)'
  },
  {
    category: 'iule', common_name: 'Gloméris', scientific_name: 'Glomeris marginata',
    difficulty: 3, humidity_min: 80, humidity_max: 95, temp_min: 12, temp_max: 20,
    sociability: 'Se garde en groupe', diet_summary: 'Détritivore : feuilles mortes de feuillus',
    vigilance: 'Craint la chaleur : jamais au-dessus de 22 °C',
    presentation: "Petit iule boule d'Europe (dont la France), de 1,5 à 2 cm, noir brillant bordé de blanc. Il se roule en boule parfaite comme un cloporte. Très long à vivre, mais il ne supporte pas la chaleur d'un intérieur en été.",
    habitat: "Petit bac frais (12-20 °C), à l'abri du soleil : terreau de forêt, mousse, épaisse couche de feuilles de chêne, hêtre ou noisetier, bois pourri et écorces. Humidité élevée mais aération correcte.",
    feeding_detail: "Feuilles mortes de feuillus bien décomposées, bois pourri, un peu de légume et de levure de bière de temps en temps. Calcium disponible.",
    repro_sexing: "Le mâle porte à l'arrière une paire de pinces (télopodes) visibles sous l'animal ; la femelle n'en a pas.",
    repro_conditions: "Cycle des saisons : une période plus fraîche en hiver, une humidité stable et une litière toujours renouvelée.",
    repro_mating: "Ponte au printemps : la femelle enferme chaque œuf dans une petite capsule de terre mâchée.",
    repro_incubation: "Quelques semaines dans le substrat.",
    repro_juveniles: "Très lents : 3 à 4 ans pour devenir adultes. Ils vivent dans la litière décomposée.",
    repro_pitfalls: "Chaleur estivale (la première cause de perte), bac qui sèche, litière de résineux ou de feuilles fraîches.",
    lifespan: "jusqu'à 10 ans et plus", size_class: 'petit', niche: 'litiere'
  },
  {
    category: 'iule', common_name: 'Iule dragon rose fluo', scientific_name: 'Desmoxytes purpurosea',
    difficulty: 3, humidity_min: 75, humidity_max: 90, temp_min: 20, temp_max: 26,
    sociability: 'Grégaire', diet_summary: 'Détritivore : feuilles, champignons, légumes',
    vigilance: "Produit du cyanure (odeur d'amande) : se laver les mains",
    presentation: "Le célèbre « shocking pink dragon » de Thaïlande, découvert en 2007 dans des grottes calcaires. Environ 3 cm, rose vif hérissé d'épines : la couleur avertit qu'il est toxique. Croissance rapide, vie courte.",
    habitat: "Bac de taille moyenne, substrat humide de 5 à 8 cm avec du calcaire (pierres, coquilles broyées), feuilles mortes, bois pourri, mousse. Humidité élevée, aération correcte, température plutôt modérée.",
    feeding_detail: "Feuilles mortes décomposées, champignons, légumes (courgette, concombre), un peu de protéines. Il mange beaucoup : la nourriture ne doit jamais manquer.",
    repro_sexing: "Gonopodes du mâle au 7e anneau, visibles à la loupe sous l'animal.",
    repro_conditions: "Nourriture abondante, humidité stable et calcium : se reproduit bien dans de bonnes conditions.",
    repro_mating: "Accouplements fréquents, ponte dans le substrat humide.",
    repro_incubation: "Quelques semaines dans le substrat.",
    repro_juveniles: "Croissance rapide, adultes en quelques mois. La colonie doit se renouveler en continu car les adultes vivent peu.",
    repro_pitfalls: "Bac trop sec, manque de nourriture, ne pas garder de jeunes : une colonie vieillissante peut s'éteindre vite.",
    lifespan: '1 à 2 ans (estimation)', size_class: 'petit', niche: 'litiere'
  }
];
