// Every mantis grows the same way: kept apart, molting hanging from the lid.
const ALONE = 'Solitaire : une mante par bac';
const MOLT = "Les jeunes muent suspendus au plafond du bac : il doit faire au moins trois fois leur longueur en hauteur, avec un couvercle en grillage.";
const SEXING = "Comptez les segments sous l'abdomen à partir du subadulte : 6 chez la femelle, 8 chez le mâle. Le mâle adulte est plus fin, avec des antennes plus longues et des ailes qui dépassent l'abdomen.";
const MATING = "Bien nourrir la femelle avant de présenter le mâle, et les surveiller : elle peut le manger. Elle pond ensuite une oothèque (une mousse qui durcit) accrochée à une branche.";

module.exports = [
  {
    category: 'mante', common_name: 'Mante africaine', scientific_name: 'Sphodromantis lineola',
    difficulty: 1, humidity_min: 50, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : mouches, grillons, blattes',
    vigilance: 'Aucune',
    presentation: "Grande mante verte d'Afrique (7 à 9 cm pour la femelle), robuste et vorace. L'espèce idéale pour commencer les mantes.",
    habitat: "Bac aéré plus haut que large, branches pour s'accrocher. Brumiser légèrement 2 ou 3 fois par semaine.",
    feeding_detail: "Drosophiles puis mouches pour les jeunes, puis grillons, mouches et blattes pour les adultes, 2 ou 3 fois par semaine.",
    repro_sexing: SEXING,
    repro_conditions: "Femelle adulte depuis 2 semaines et bien nourrie.",
    repro_mating: MATING,
    repro_incubation: "4 à 6 semaines à 26-28 °C.",
    repro_juveniles: "100 à 200 petits par oothèque ; les séparer vite (cannibalisme). " + MOLT,
    repro_pitfalls: "Jeunes laissés ensemble, mues ratées (bac trop sec ou trop bas).",
    lifespan: 'environ 1 an', size_class: 'grand'
  },
  {
    category: 'mante', common_name: 'Mante géante asiatique', scientific_name: 'Hierodula membranacea',
    difficulty: 1, humidity_min: 50, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : mouches, grillons, blattes',
    vigilance: 'Aucune',
    presentation: "Grande mante d'Asie (jusqu'à 10 cm), verte ou brune, très vorace et facile.",
    habitat: "Bac aéré et haut, branches. Brumisage léger.",
    feeding_detail: "Mouches, grillons, blattes ; 2 ou 3 proies par semaine pour un adulte.",
    repro_sexing: SEXING,
    repro_conditions: "Femelle bien nourrie.",
    repro_mating: MATING,
    repro_incubation: "4 à 6 semaines.",
    repro_juveniles: "Nombreux petits, à séparer rapidement. " + MOLT,
    repro_pitfalls: "Cannibalisme, mues ratées.",
    lifespan: 'environ 1 an', size_class: 'grand'
  },
  {
    category: 'mante', common_name: 'Mante religieuse', scientific_name: 'Mantis religiosa',
    difficulty: 2, humidity_min: 40, humidity_max: 60, temp_min: 20, temp_max: 28,
    sociability: ALONE, diet_summary: 'Prédateur : mouches, criquets, grillons',
    vigilance: "Protégée dans certaines régions (Île-de-France) : ne pas la prélever",
    presentation: "La mante de chez nous (5 à 7,5 cm), verte ou brune. Les adultes meurent à l'automne et l'oothèque passe l'hiver avant d'éclore au printemps.",
    habitat: "Bac aéré et haut, branches, herbes sèches. Brumisage léger.",
    feeding_detail: "Mouches, criquets, grillons, papillons.",
    repro_sexing: SEXING,
    repro_conditions: "Saison estivale, femelle bien nourrie.",
    repro_mating: MATING,
    repro_incubation: "L'oothèque a besoin d'un vrai hiver : 2 à 3 mois au frais (5-10 °C, dehors à l'abri), puis éclosion au printemps.",
    repro_juveniles: "Nombreux petits à séparer. " + MOLT,
    repro_pitfalls: "Oothèque gardée au chaud tout l'hiver (pas d'éclosion), prélèvement dans la nature.",
    lifespan: 'environ 1 an (une saison)'
  },
  {
    category: 'mante', common_name: 'Mante fantôme', scientific_name: 'Phyllocrania paradoxa',
    difficulty: 2, humidity_min: 60, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: 'Tolère des congénères bien nourris', diet_summary: 'Prédateur : mouches, petits grillons',
    vigilance: 'Aucune',
    presentation: "Petite mante d'Afrique (5 cm) qui imite une feuille morte froissée, avec une couronne sur la tête. Calme, peu cannibale.",
    habitat: "Bac aéré et haut, branches et feuilles sèches. Brumisage tous les 2 jours.",
    feeding_detail: "Mouches, petits grillons, papillons.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, humidité moyenne.",
    repro_mating: MATING,
    repro_incubation: "4 à 6 semaines.",
    repro_juveniles: "20 à 40 petits. " + MOLT,
    repro_pitfalls: "Bac trop sec à la mue.",
    lifespan: 'environ 1 an', size_class: 'moyen'
  },
  {
    category: 'mante', common_name: 'Mante fleur à bandes', scientific_name: 'Creobroter gemmatus',
    difficulty: 2, humidity_min: 60, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : mouches, petits insectes volants',
    vigilance: 'Aucune',
    presentation: "Petite mante fleur d'Asie (3,5 à 4 cm), crème et verte, avec une tache en forme d'œil sur les ailes.",
    habitat: "Petit bac aéré et haut, branches fines. Brumisage tous les 2 jours.",
    feeding_detail: "Drosophiles pour les petits, puis mouches et petits insectes volants.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, humidité moyenne.",
    repro_mating: MATING,
    repro_incubation: "4 à 6 semaines.",
    repro_juveniles: "À séparer. " + MOLT,
    repro_pitfalls: "Proies trop grosses, bac trop sec.",
    lifespan: 'environ 8 mois à 1 an', size_class: 'moyen'
  },
  {
    category: 'mante', common_name: 'Mante fleur épineuse', scientific_name: 'Pseudocreobotra wahlbergii',
    difficulty: 3, humidity_min: 50, humidity_max: 70, temp_min: 24, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : insectes volants',
    vigilance: 'Aucune',
    presentation: "Mante fleur d'Afrique (4 cm) aux ailes marquées d'une spirale en forme d'œil, couverte d'épines. Superbe, plus délicate à élever.",
    habitat: "Bac aéré et haut, bonne ventilation, branches fines. Brumisage tous les 2 jours.",
    feeding_detail: "Uniquement des insectes volants : drosophiles, mouches, papillons.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur, aération, proies volantes variées.",
    repro_mating: MATING,
    repro_incubation: "4 à 6 semaines.",
    repro_juveniles: "Petits délicats, à nourrir de drosophiles. " + MOLT,
    repro_pitfalls: "Proies rampantes seulement, bac confiné.",
    lifespan: 'environ 8 mois à 1 an', size_class: 'moyen'
  },
  {
    category: 'mante', common_name: 'Mante feuille morte géante', scientific_name: 'Deroplatys desiccata',
    difficulty: 3, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : mouches, grillons, blattes',
    vigilance: 'Aucune',
    presentation: "Grande mante de Malaisie (7 à 8 cm) au thorax élargi en feuille sèche. Un camouflage spectaculaire, une mante calme.",
    habitat: "Bac aéré et haut, branches et feuilles sèches, humidité plus élevée que la moyenne des mantes.",
    feeding_detail: "Mouches, grillons, blattes.",
    repro_sexing: SEXING,
    repro_conditions: "Chaleur et humidité.",
    repro_mating: MATING,
    repro_incubation: "6 à 8 semaines.",
    repro_juveniles: "Petits sensibles à la sécheresse. " + MOLT,
    repro_pitfalls: "Bac trop sec à la mue.",
    lifespan: 'environ 1 an', size_class: 'grand'
  },
  {
    category: 'mante', common_name: 'Mante orchidée', scientific_name: 'Hymenopus coronatus',
    difficulty: 4, humidity_min: 60, humidity_max: 80, temp_min: 25, temp_max: 30,
    sociability: ALONE, diet_summary: 'Prédateur : insectes volants',
    vigilance: 'Aucune',
    presentation: "La célèbre mante d'Asie qui imite une fleur d'orchidée blanche et rose. Les femelles (6 cm) grandissent bien plus lentement que les mâles (2,5 cm), ce qui complique l'accouplement.",
    habitat: "Bac aéré et haut, ventilation importante, branches fines. Brumisage quotidien léger, jamais de bac confiné.",
    feeding_detail: "Insectes volants : drosophiles, mouches, papillons.",
    repro_sexing: SEXING,
    repro_conditions: "Garder les mâles au frais pour ralentir leur croissance et les avoir adultes en même temps que les femelles.",
    repro_mating: MATING,
    repro_incubation: "5 à 7 semaines.",
    repro_juveniles: "Les petits, rouges et noirs, imitent des punaises ; très délicats. " + MOLT,
    repro_pitfalls: "Mâles et femelles adultes en décalé, bac confiné, proies rampantes.",
    lifespan: 'environ 8 mois (femelle), moins pour le mâle', size_class: 'moyen'
  },
  {
    category: 'mante', common_name: 'Mante diable fleur', scientific_name: 'Idolomantis diabolica',
    difficulty: 5, humidity_min: 40, humidity_max: 60, temp_min: 26, temp_max: 35,
    sociability: ALONE, diet_summary: 'Prédateur : uniquement insectes volants',
    vigilance: 'Élevage expert',
    presentation: "La plus spectaculaire des mantes (jusqu'à 13 cm), d'Afrique de l'Est, aux pattes avant colorées qu'elle déploie pour impressionner. Très exigeante.",
    habitat: "Grand bac très haut et très aéré, chaleur forte le jour (30-35 °C) et plus fraîche la nuit, humidité basse. Brumisage léger.",
    feeding_detail: "Uniquement des insectes volants : mouches, papillons. Elle refuse les grillons.",
    repro_sexing: SEXING,
    repro_conditions: "Grande chaleur, aération, beaucoup de place pour les mues.",
    repro_mating: MATING,
    repro_incubation: "6 à 8 semaines.",
    repro_juveniles: "Petits délicats ; mues longues et difficiles. " + MOLT,
    repro_pitfalls: "Bac trop petit (mues ratées), humidité trop élevée, proies non volantes.",
    lifespan: 'environ 1 an', size_class: 'grand'
  }
];
