const TALL = "Bac aéré au moins trois fois plus haut que l'insecte, pour les mues ; les feuilles en bouquet dans un pot d'eau fermé (pour que les jeunes ne s'y noient pas).";

module.exports = [
  {
    category: 'phasme', common_name: 'Phasme bâton', scientific_name: 'Carausius morosus',
    difficulty: 1, humidity_min: 50, humidity_max: 70, temp_min: 20, temp_max: 25,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, troène, lierre, rosier',
    vigilance: 'Ne jamais relâcher œufs ni insectes dehors',
    presentation: "Le phasme d'Inde des classes d'école : 8 à 10 cm, vert ou brun, femelles seules qui se reproduisent sans mâle. Le plus facile de tous.",
    habitat: TALL + " Brumisage léger tous les 2 ou 3 jours.",
    feeding_detail: "Ronce, troène, lierre, rosier, laitue en dépannage.",
    repro_sexing: "Presque toujours des femelles : la reproduction se fait sans mâle (parthénogenèse).",
    repro_conditions: "Facile à température ambiante.",
    repro_mating: "Les œufs, comme des graines, tombent au fond du bac.",
    repro_incubation: "2 à 4 mois sur du sable ou de la fibre de coco légèrement humide.",
    repro_juveniles: "Petits à mettre sur de la ronce jeune ; adultes en 4 à 5 mois.",
    repro_pitfalls: "Surpopulation, œufs jetés à l'extérieur (espèce qui peut s'installer dans la nature).",
    lifespan: 'environ 1 an'
  },
  {
    category: 'phasme', common_name: 'Phasme du Vietnam', scientific_name: 'Medauroidea extradentata',
    difficulty: 1, humidity_min: 50, humidity_max: 70, temp_min: 20, temp_max: 25,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, noisetier',
    vigilance: 'Aucune',
    presentation: "Phasme bâton brun du Vietnam (10 à 12 cm) aux petites cornes sur la tête. Facile, se reproduit souvent sans mâle.",
    habitat: TALL + " Brumisage léger.",
    feeding_detail: "Ronce, chêne, noisetier, rosier.",
    repro_sexing: "Le mâle, rare, est plus fin et plus petit.",
    repro_conditions: "Facile à température ambiante.",
    repro_mating: "Œufs lâchés au sol.",
    repro_incubation: "3 à 5 mois sur substrat légèrement humide.",
    repro_juveniles: "Adultes en 4 à 6 mois.",
    repro_pitfalls: "Ronce sèche, surpopulation.",
    lifespan: 'environ 1 an'
  },
  {
    category: 'phasme', common_name: 'Phasme des Philippines', scientific_name: 'Sungaya inexpectata',
    difficulty: 1, humidity_min: 60, humidity_max: 80, temp_min: 20, temp_max: 26,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, noisetier',
    vigilance: 'Aucune',
    presentation: "Phasme trapu des Philippines (6 à 8 cm), brun, qui vit au sol plutôt que dans les branches. Les femelles se reproduisent sans mâle.",
    habitat: "Bac plus large que haut, 5 cm de substrat humide (fibre de coco), écorces et feuillage. Brumisage tous les 2 jours.",
    feeding_detail: "Ronce, chêne, noisetier, goyavier.",
    repro_sexing: "Surtout des femelles (parthénogenèse).",
    repro_conditions: "Substrat humide pour la ponte.",
    repro_mating: "La femelle enterre ses œufs dans le substrat.",
    repro_incubation: "3 à 4 mois.",
    repro_juveniles: "Adultes en 4 à 6 mois.",
    repro_pitfalls: "Substrat sec.",
    lifespan: 'environ 1 an', size_class: 'moyen', niche: 'litiere'
  },
  {
    category: 'phasme', common_name: 'Phasme feuille épineux', scientific_name: 'Extatosoma tiaratum',
    difficulty: 2, humidity_min: 50, humidity_max: 70, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, eucalyptus, chêne, rosier',
    vigilance: 'Aucune',
    presentation: "Phasme d'Australie : la femelle (12 à 15 cm), épaisse et épineuse, ressemble à un paquet de feuilles sèches ; le mâle, ailé, est plus fin. Les jeunes imitent des fourmis.",
    habitat: TALL + " Bac de 60 cm de haut au moins pour les femelles. Brumisage tous les 2 jours.",
    feeding_detail: "Ronce, eucalyptus, chêne, rosier, framboisier.",
    repro_sexing: "Femelle grosse et épineuse, mâle fin et ailé.",
    repro_conditions: "Mâles et femelles ensemble (la femelle peut aussi pondre sans mâle).",
    repro_mating: "La femelle lance ses œufs au sol.",
    repro_incubation: "4 à 8 mois, plus long sans fécondation.",
    repro_juveniles: "Adultes en 4 à 6 mois.",
    repro_pitfalls: "Bac trop bas, nourriture fanée.",
    lifespan: '1 an à 1 an et demi'
  },
  {
    category: 'phasme', common_name: 'Phasme du Pérou', scientific_name: 'Peruphasma schultei',
    difficulty: 2, humidity_min: 50, humidity_max: 70, temp_min: 20, temp_max: 25,
    sociability: 'Groupe', diet_summary: 'Herbivore : troène uniquement',
    vigilance: 'Projette un liquide irritant pour les yeux',
    presentation: "Phasme noir velours (5 à 6 cm) aux yeux jaunes et aux ailes rouges, venu du Pérou. Superbe, mais il ne mange que du troène.",
    habitat: TALL + " Brumisage léger.",
    feeding_detail: "Troène (Ligustrum) toute l'année : vérifier qu'on en a accès avant de l'adopter.",
    repro_sexing: "Le mâle est plus petit et plus fin.",
    repro_conditions: "Troène frais en continu.",
    repro_mating: "Œufs lâchés au sol.",
    repro_incubation: "3 à 4 mois.",
    repro_juveniles: "Adultes en 4 à 5 mois.",
    repro_pitfalls: "Manque de troène, manipulation près du visage.",
    lifespan: 'environ 1 an', size_class: 'moyen'
  },
  {
    category: 'phasme', common_name: 'Phasme épineux de Nouvelle-Guinée', scientific_name: 'Eurycantha calcarata',
    difficulty: 2, humidity_min: 70, humidity_max: 80, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, lierre',
    vigilance: 'Le mâle pince avec ses pattes arrière épineuses',
    presentation: "Grand phasme trapu et épineux (12 à 15 cm), brun foncé, nocturne. Les mâles portent un énorme éperon sur les pattes arrière.",
    habitat: "Bac aéré, écorces creuses et liège pour se cacher le jour, substrat humide pour la ponte. Brumisage tous les 2 jours.",
    feeding_detail: "Ronce, chêne, lierre, eucalyptus, goyavier.",
    repro_sexing: "Le mâle a des pattes arrière très épaisses avec un grand éperon ; la femelle a un ovipositeur pointu au bout de l'abdomen.",
    repro_conditions: "Humidité et cachettes.",
    repro_mating: "La femelle enterre ses œufs dans le substrat humide.",
    repro_incubation: "4 à 6 mois.",
    repro_juveniles: "Adultes en 6 à 8 mois.",
    repro_pitfalls: "Substrat sec, manque de cachettes.",
    lifespan: '1 an et demi à 2 ans'
  },
  {
    category: 'phasme', common_name: 'Phyllie des Philippines', scientific_name: 'Phyllium philippinicum',
    difficulty: 3, humidity_min: 60, humidity_max: 80, temp_min: 22, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, goyavier',
    vigilance: 'Aucune',
    presentation: "Le phasme feuille : un insecte plat et vert qui imite parfaitement une feuille, jusqu'aux nervures et aux traces de morsure. Les jeunes sont délicats.",
    habitat: TALL + " Bonne aération, brumisage quotidien léger.",
    feeding_detail: "Ronce, chêne, goyavier. Pour les nouveau-nés, couper le bord des feuilles de ronce : ils ont du mal à commencer une feuille entière.",
    repro_sexing: "Femelle large ; mâle fin, ailé et brunâtre.",
    repro_conditions: "Humidité, aération, ronce fraîche.",
    repro_mating: "Œufs lâchés au sol (souvent sans mâle).",
    repro_incubation: "3 à 6 mois.",
    repro_juveniles: "Les petits, rouges à la naissance, deviennent verts en mangeant. Adultes en 4 à 6 mois.",
    repro_pitfalls: "Premiers stades qui ne mangent pas, bac confiné.",
    lifespan: 'environ 1 an', size_class: 'moyen'
  },
  {
    category: 'phasme', common_name: 'Phasme de Malaisie', scientific_name: 'Heteropteryx dilatata',
    difficulty: 3, humidity_min: 70, humidity_max: 80, temp_min: 24, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, goyavier',
    vigilance: 'Pince et se défend avec ses pattes épineuses',
    presentation: "Le « phasme nymphe des bois » : la femelle, vert pomme, dépasse 15 cm et pèse plusieurs dizaines de grammes, un des insectes les plus lourds du monde. Le mâle, brun, est plus petit et ailé.",
    habitat: "Grand bac aéré et haut, 10 cm de substrat humide pour la ponte, brumisage quotidien.",
    feeding_detail: "Ronce, chêne, goyavier, eucalyptus.",
    repro_sexing: "Femelle verte massive avec ovipositeur ; mâle brun et ailé.",
    repro_conditions: "Chaleur et humidité, substrat de ponte profond.",
    repro_mating: "La femelle enterre ses gros œufs dans le substrat.",
    repro_incubation: "8 à 14 mois, à garder humides.",
    repro_juveniles: "Adultes en 1 an environ.",
    repro_pitfalls: "Œufs qui sèchent pendant la longue incubation, bac trop petit.",
    lifespan: '2 à 3 ans en tout'
  },
  {
    category: 'phasme', common_name: 'Phasme bleu de Madagascar', scientific_name: 'Achrioptera manga',
    difficulty: 3, humidity_min: 50, humidity_max: 60, temp_min: 24, temp_max: 28,
    sociability: 'Groupe', diet_summary: 'Herbivore : ronce, chêne, eucalyptus',
    vigilance: "Souvent vendu sous le nom d'Achrioptera fallax",
    presentation: "Grand phasme de Madagascar : le mâle est d'un bleu électrique, la femelle brune et plus grosse. La plupart des élevages vendus comme « fallax » sont en fait cette espèce, décrite en 2019.",
    habitat: TALL + " Bonne aération, un linge humide au fond pour l'humidité.",
    feeding_detail: "Ronce, chêne, eucalyptus. Éviter les jeunes pousses de printemps, mal tolérées (diarrhée).",
    repro_sexing: "Mâle bleu et fin ; femelle brune, plus grosse.",
    repro_conditions: "Chaleur, aération, feuillage mûr.",
    repro_mating: "La femelle pond dans le sol.",
    repro_incubation: "4 à 5 mois sur sable légèrement humide à 20-23 °C ; un peu de mousse sèche dessus aide l'éclosion.",
    repro_juveniles: "Adultes en 5 à 6 mois.",
    repro_pitfalls: "Feuilles tendres de printemps, mues ratées par manque d'humidité.",
    lifespan: 'environ 8 à 10 mois'
  }
];
